### ISSUE TITLE
Clicking magnifying glass does nothing

### ISSUE THREAD

**Issue by BustedSec** [stnkl/EverythingToolbar#103]
After toolbar install, clicking the magnifying glass does not pop open search windows. Right click options show up.

**Comment by Horst12** [comment]
There is no pop-up, you have to enlarge the icon on the taskbar.

**Comment by stnkl** [comment]
> There is no pop-up, you have to enlarge the icon on the taskbar.

Yes, it should pop out the search results window when clicking the magnifying glass.

> After toolbar install, clicking the magnifying glass does not pop open search windows. Right click options show up.

Could you please show a screenshot of the context menu you are seeing? There should not be any context menu when right clicking the magnifying glass. Also please report your version of EverythingToolbar, Windows and attach your log file at `%Temp%\EverythingToolbar.log`.

**Comment by BustedSec** [comment]
[image: image.png]
2021-02-01 13:46:25.0714|INFO|EverythingToolbar|EverythingToolbar started.
Version: 0.2.3.0, OS: Microsoft Windows NT 10.0.19042.0
2021-02-01 13:46:40.0432|INFO|EverythingToolbar|EverythingToolbar started.
Version: 0.2.3.0, OS: Microsoft Windows NT 10.0.19042.0
2021-02-01 13:47:40.9191|INFO|EverythingToolbar|EverythingToolbar started.
Version: 0.2.3.0, OS: Microsoft Windows NT 10.0.19042.0
2021-02-01 13:49:35.5604|INFO|EverythingToolbar|EverythingToolbar started.
Version: 0.2.3.0, OS: Microsoft Windows NT 10.0.19042.0
2021-02-01 13:53:13.4770|INFO|EverythingToolbar|EverythingToolbar started.
Version: 0.2.3.0, OS: Microsoft Windows NT 10.0.19042.0

I don't seem to have the ability to resize the magnifying glass area. I can
type into it and I see the screen pops up but I cannot see what I am typing
in because the area is too small.

**Comment by stnkl** [comment]
To resize the toolbar you have to right click an empty area on your taskbar and uncheck "Lock the taskbar". Small handles appear allowing you to adjust the size. See the [installation video](https://user-images.githubusercontent.com/17520641/102831521-4ee67100-43ec-11eb-8804-42dda8affba1.gif) for reference.

Also you are using a really old version of EverythingToolbar (0.2.3). Please update to the [latest version](https://github.com/stnkl/EverythingToolbar/releases) (the latest beta seems stable as well). Make sure to uninstall the current version by running `uninstall.cmd` as admin beforehand.

**Comment by BustedSec** [comment]
thanks, I should have totally realized that.
