### ISSUE TITLE
Don't close toolbar on Alt + Tab during drag and drop

### ISSUE THREAD

**Issue by LinqLover** [stnkl/EverythingToolbar#104]
A helpful (even though much less known) trick for drag and drop is to:

1. drag an object, e.g. a file, from the source application
2. press Alt + Tab to switch to target application (still keeping your mouse button pressed), and
3. drop your object in the target application.

When I tried to apply this workflow with EverythingToolbar as the source application (because it occluded my target application), the DnD failed because the toolbar disappeared upon Alt + Tab.

It would be great if the automatic closing of ET could be disabled during DnD.

**Comment by Horst12** [comment]
I use drag and drop to the target application on the taskbar.
This works for any program which is already running and shown in the taskbar.

**Comment by LinqLover** [comment]
This does not either work for me. When dragging a file from ET onto the taskbar (without releasing the mouse button), the toolbar disappears and I am unable to drop the file into any application (without going over the taskbar, though, this works fine). But an interesting consequence is that the taskbar now does not react any longer on right-clicks or also custom 7+ taskbar tweaker events ...

Apart from this, I think both workflows should work since they work everywhere else in Windows. Your workflow, for example, has the disadvantage of not working well when there are many windows in the taskbar and it maybe even has a scrollbar or the target window is not shown in the taskbar. :-)

**Comment by stnkl** [comment]
This issue has been addressed in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0).
