### ISSUE TITLE
ET cannot be shown on secondary screen taskbars

### ISSUE THREAD

**Issue by LinqLover** [stnkl/EverythingToolbar#105]
ET can ATM only be shown in the taskbar of the primary screen because Windows only supports custom symbol bars there. Probably this is a "won't fix", but wouldn't it possible to hijack the existing "Windows search" icon instead? Then it would also be possible to display the magnifying glass before the task view icon. :-)

**Comment by stnkl** [comment]
Not a "won't fix" but rather "duplicate" of #63. It might come at some point, but I'm not sure how and when yet.
