### ISSUE TITLE
[Question] I have some doubts about the edition of a custom theme.

### ISSUE THREAD

**Issue by Dhyfer1** [stnkl/EverythingToolbar#106]
Hi @stnkl 👋

I have been making my own custom theme based on one of the built-in themes, and I have been able to customize every line in the theme file as well as see the result of the editing in EverythingToolbar, but so far I have been unable to see any change when I edit these lines:
```xaml
    <SolidColorBrush x:Key="SearchBoxForeground" Color="#ffdadada" />
    <SolidColorBrush x:Key="SearchBoxForegroundHover" Color="#ffdadada" />
    <SolidColorBrush x:Key="SearchBoxForegroundActive" Color="#ff2b2b2b" />
```
When I change the color value for `SearchBoxForegroundActive` I can see that its effect on the search box is to change the color of the text cursor and the typed text, but for `SearchBoxForeground` and `SearchBoxForegroundHover` I've changed their color values many times, but I haven't been able to see what changes they make in the search box of EverythingToolbar.

So can you tell me what changes they make to the search box after they are edited? How to leave the search box on the foreground to see the changes?

I look forward to your reply.

**Comment by stnkl** [comment]
Hi! "Foreground" always means text color. The `SearchBoxForegroundActive` - as you already said - is the text color of the active search box (active meaning keyboard focused). `SearchBoxForeground` and `SearchBoxForegroundHover` define the text color in unfocused state and when the mouse hovers over the search box. However currently the search box always automatically clears its content when it gets unfocused so it will always be empty when it's not currently focused. That means they are basically unused at the moment.

**Comment by Dhyfer1** [comment]
> `SearchBoxForeground` and `SearchBoxForegroundHover` define the text color in unfocused state and when the mouse hovers over the search box. However currently the search box always automatically clears its content when it gets unfocused so it will always be empty when it's not currently focused. That means they are basically unused at the moment.

Thank you for responding!
Ok, I understand. It is true, when there is text in the search box and when you click out of the box, the text that was there is deleted. So those two lines of code are useless for now as they have no effect on the theme, did I understand correctly?

**Comment by stnkl** [comment]
Yes, that is correct.

**Comment by Dhyfer1** [comment]
Okay, thank you for your attention to my issue. You can close it. 🙂
