### ISSUE TITLE
Shortcut should also raise the toolbar when it's hidden

### ISSUE THREAD

**Issue by ziplock9000** [stnkl/EverythingToolbar#107]
It doesn't behave well when the toolbar is set to audio hide. There's no visual feedback the search box got text context and you can't see what you're typing

**Comment by stnkl** [comment]
That is a known issue. See #4

**Comment by ziplock9000** [comment]
It's not the same thing. This is to open the toolbar in the first place. It's as if you pressed the Windows key, then pressed Windows+Alt+S

**Comment by stnkl** [comment]
Yes, the taskbar should always be visible while the search box is focused.
