### ISSUE TITLE
Keep last search results

### ISSUE THREAD

**Issue by JoAllg** [stnkl/EverythingToolbar#108]
edit: I've just seen that a similar request was made in #24 . My request has a different touch but I think they could work together.

Currently the last search is lost as soon as the toolbar is closed. This happens for example when interacting with a search result.
I happen to need to search for the same thing multiple times because I didn't get the right result / folder  or want to interact with several of the search results.

Everything itself does keep the last result, could you implement that too?
It would be best if it does not search again when opening the Toolbar but keeps the last search+results in cache.
Win + Alt + S could then mark the previous search text to be able to directly replace it with a new searchy. The same when pressing the search icon in the taskbar.

**Comment by stnkl** [comment]
This issue has been addressed in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0).
