### ISSUE TITLE
Conflicting with MacType

### ISSUE THREAD

**Issue by jordanyoong1** [stnkl/EverythingToolbar#117]
MacType does have a feature that you can whitelist specific process but I can't seem to find a running exe related to this App. It there a way to solve this?

![image](https://user-images.githubusercontent.com/40160073/108246835-dbaf7000-718c-11eb-92fc-bc84b0b2cc69.png)

**Comment by stnkl** [comment]
The EverythingToolbar.dll gets loaded by explorer.exe. Can you whitelist by window name "Deskband host for wpf"? It shows like this in Spy++:

![image](https://user-images.githubusercontent.com/17520641/108248738-86576c80-7154-11eb-8346-3128f463b58f.png)
