### ISSUE TITLE
Is there any way to change font?

### ISSUE THREAD

**Issue by Keaveth** [stnkl/EverythingToolbar#119]
So far i love EverythingToolbar, but is there a way to change default font? Would make custom theming even better

**Comment by stnkl** [comment]
You can only change the [font family](https://docs.microsoft.com/de-de/dotnet/api/system.windows.media.fontfamily?view=net-5.0) of search result templates by changing the corresponding files within `ÌtemTemplates`. You can currently not change it for the tabs or search box.

**Comment by Keaveth** [comment]
Thank you for your response

**Comment by stnkl** [comment]
I will close this issue as it will be tracked under the more general #147.
