### ISSUE TITLE
installer EverythingToolbar-0.6.2.msi has problem

### ISSUE THREAD

**Issue by huangchaof** [stnkl/EverythingToolbar#120]
MY OS is win10 home 1909, .Net framework 4.8, i used the installer "EverythingToolbar-0.6.2.msi", the taskbar couldn't have the **search bar**. So i turned to use "EverythingToolbar-0.6.2-beta3.zip" install , and it success， works well.
Please check this installer

**Comment by stnkl** [comment]
Did you have an earlier version installed prior to using the installer? After the installation you have to open the task bar context menu twice for EverythingToolbar to show up. Did you do that?

**Comment by huangchaof** [comment]
hi @stnkl
1. it's my first time to use EverythingToolbar, never installed  earlier version. 
2. After the installation of "EverythingToolbar-0.6.2.msi",  i could see the EverythingToolbar on the  task bar context menu "tool "，and i clicked on EverythingToolbar with left mouse , then nothing happened (no  tick before EverythingToolbar, no search bar)

**Comment by huangchaof** [comment]
i just uninstalled , and use msi file reinstalled , then record this video , it show the problem
https://user-images.githubusercontent.com/42507015/108622347-2d991400-7473-11eb-8d6c-eae444cdc5b3.mp4

**Comment by stnkl** [comment]
Thanks! Could you please upload the log file at `%TEMP%\EverythingToolbar.log`? Also which path did you install it to?

**Comment by huangchaof** [comment]
@stnkl 
pls see the attached file , the log seems normally
![QQ截图20210221184757](https://user-images.githubusercontent.com/42507015/108622694-794cbd00-7475-11eb-99b4-7dd3a7fb5691.jpg)


[EverythingToolbar.log](https://github.com/stnkl/EverythingToolbar/files/6017553/EverythingToolbar.log)

**Comment by stnkl** [comment]
The msi-installer of 0.6.2 should actually report as 0.6.2.1 in the log file. This indicates it doesn't even load the dll. Could you check one last thing in the registry please?

![image](https://user-images.githubusercontent.com/17520641/108622974-9b761900-743c-11eb-9d42-10779a3e64d3.png)

Does it have the correct entries in here as shown in the screenshot?

**Comment by huangchaof** [comment]
HKEY_CLASSES_ROOT\CLSID\{9D39B79C-E03C-4757-B1B6-ECCE843748F3}\InprocServer32
![注册表](https://user-images.githubusercontent.com/42507015/108623223-d433e380-7478-11eb-99bd-0154f23c263e.jpg)
my registry looks the same to this screenshot

**Comment by danielmzy** [comment]
same issue

**Comment by stnkl** [comment]
I have the same problem when trying to install EverythingToolbar within a Windows Sandbox. It seems to work fine when I change the installer to install per machine rather than per user but I am not sure why yet.

Does your Windows user account have any kind of non-standard permissions that might play a role here?

**Comment by tristansly** [comment]
Same problem here, and I have hella permission problems in my windows install rn... Honestly I'm not sure how to approach it. Tried running "Junction Box"

**Comment by KKKBoy-cpu** [comment]
I have the same problem! Why not fix it?

**Comment by stnkl** [comment]
I did some work on that but I am fairly busy at the moment. For now I would suggest installing an older release instead.

**Comment by MagicMarvel** [comment]
I have the same problem

**Comment by stnkl** [comment]
I changed the installer to install per machine rather than per user. I still don't know why this causes problems but at least this should fix it. Unfortunately it won't be possible to install without user elevation anymore.

Could you please try this installer? Please uninstall all previous versions of EverythingToolbar before running the installer for 0.6.3.

[EverythingToolbar-0.6.3.zip](https://github.com/stnkl/EverythingToolbar/files/6216538/EverythingToolbar-0.6.3.zip)

**Comment by KKKBoy-cpu** [comment]
The display position is wrong, and the original search box is not been replaced. This BUG is still not been fixed.&nbsp;I really admire you!!!

**Comment by stnkl** [comment]
> The display position is wrong, and the original search box is not been replaced. This BUG is still not been fixed.&nbsp;I really admire you!!!

Please check the [installation video](https://user-images.githubusercontent.com/17520641/107118574-19a1bf80-6882-11eb-843a-7e854e5d0684.gif) on how to move the toolbar position. EverythingToolbar is not meant to replace the original Windows 10 search box. You can disable the original one via the taskbar context menu.

Did the installation work though?

**Comment by tristansly** [comment]
Yes, can drag it into the left spot, you just can't be, you know, dumb
about it.

Finest Regards
Also what is the KKK about in your name, are you a white supremacist? If
so, kindly fuck off. If not you might think about a name change.

**Comment by gggirlgeek** [comment]
This installs OK for me v0.6.3 but I had to take ownership of the Everything install folder in Program Files. I did see search results on my taskbar. Just FYI I installed the .msi as Admin and ran Everything as Admin too. I had a bunch of other problems so I'll post about those elsewhere. Thank you.

**Comment by stnkl** [comment]
The problem seems to be resolved with version 0.6.3. Therefore closing this issue now.
