### ISSUE TITLE
Open everything search bar with keyboard shortcut

### ISSUE THREAD

**Issue by MatanAvitan** [stnkl/EverythingToolbar#121]
I have a question that I couldn't find any documentation for, 
Is there a way to open the Everything search bar with keyboard shortcut? (Like WinKey).
Thanks in advance.

**Comment by stnkl** [comment]
Yes, the default is <kbd>Win</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd> but it can be customized in the settings.

**Comment by MatanAvitan** [comment]
Thanks!
