### ISSUE TITLE
Although all requirements are met, it still cannot install.

### ISSUE THREAD

**Issue by xxkglz** [stnkl/EverythingToolbar#122]
![SharedScreenshot](https://user-images.githubusercontent.com/21968397/109592220-dddcdb80-7b49-11eb-9c3f-c26db048cfee.jpg)
Maybe the developer can explain the problem and offer a solution? I cannot install it at all, which makes me upset.
the code are following:
RegAsm : error RA0000 : 无法定位输入程序集“C:\Program Files (x86)\Everything\EverythingToolbar-master\EverythingToolbar\tools\..\bin\Release\EverythingToolbar.dll”或它的一个依赖项。
请按任意键继续. . .

**Comment by xxkglz** [comment]
Some setting information:
NET Framework Version :  REG_SZ    4.8.04084
Everything Version : 1.4.1.1005
Windows Version : windows 10 20H2

**Comment by stnkl** [comment]
I think you downloaded the code. Please download the installer from the releases page instead: https://github.com/stnkl/EverythingToolbar/releases

**Comment by xxkglz** [comment]
> I think you downloaded the code. Please download the installer (EverythingToolbar-0.6.2.msi) from the releases page instead: https://github.com/stnkl/EverythingToolbar/releases

Case closed！！Thank you from the bottom of my heart！！😉
