### ISSUE TITLE
How do i put Every thing tool bar on the left side？

### ISSUE THREAD

**Issue by ghost** [stnkl/EverythingToolbar#123]
I kinda want to put the search bar on the left side like the windows default one ,but it stay on the right side and I don't know how to move it...

**Comment by stnkl** [comment]
Hi, have a look at the [demo video](https://user-images.githubusercontent.com/17520641/107118574-19a1bf80-6882-11eb-843a-7e854e5d0684.gif). Remember to unlock the taskbar so you can grab the handles.

**Comment by kasusa** [comment]
thank you!
i underatand how to drag it now

**Comment by sigrain1** [comment]
is there any way to do this in windows 11?
