### ISSUE TITLE
Can a named Everything instance be used instead of the default ?

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#124]
As the subject says, I want to use a named instance, currently for testing the new Everything 1.5
[Edit]
I found a way to use it by adding **alpha_instance=0** into the Everything-1.5a.ini

**Comment by stnkl** [comment]
Sorry for the late response. Glad you found a workaround to use EverythingToolbar with 1.5!

For reference (in case somebody else wants to use Everything 1.5): https://www.voidtools.com/forum/viewtopic.php?p=35699

**Comment by Horst12** [comment]
Please note that the Everything Filters.csv has changed its format.
I use a copy of the old one for the Toolbar.

**Comment by stnkl** [comment]
Thanks for the heads up. I will add full support for 1.5 once it's fully released. Right now the SDK has not been released and things might change so I can't really add support at this point.
