### ISSUE TITLE
Refuses to run with Everything's -instance parameter (alongside other instances of Everything.)

### ISSUE THREAD

**Issue by gggirlgeek** [stnkl/EverythingToolbar#126]
Hello and thanks for the free software.

I got v0.6.3 installed today and I finally got it working after I deleted all my settings and data (Everything.ini and Everything.db.) Then I moved Everything from my second hard dive into Program Files and took ownership of the folder. Windows did not want to let me access it so I assumed the permissions were the problem. Symlinks were no help either but this is not a deal-breaker for me.

I finally got EverythingToolbar to run in a barebones state but I need to run multiple instances of Everything for different types of indexing. The toolbar refused to search as long as Everything was running with the -instance parameter. I even tried running it in normal mode while other instances ran in the background. I always got the same error in the log: 
```
2021-03-31 04:11:58.2474|INFO|EverythingToolbar started. Version: 0.6.3.0, OS: Microsoft Windows NT 10.0.19041.0
2021-03-31 04:11:58.3487|ERROR|IPC is not available.
2021-03-31 04:11:58.3487|ERROR|Failed to get Everything version number. Is Everything running?
```
----------------
Everything x64 v1.4.1.005

**Comment by stnkl** [comment]
Hi, thanks for opening the issue!

The current version of the Everything SDK does not support named instance support. This means you can not use EverythingToolbar with the `-instance` parameter. That might change in the upcoming version 1.5 of Everything but we'll see.

The install location and folder permissions of Everything itself should not have any effect on whether EverythingToolbar works or not. I suspect there was another problem with your Everything installation. Maybe you had the Lite version installed or were using a named instance.
