### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by Anshulgada** [stnkl/EverythingToolbar#128]
When I run install cmd as admin, it shows me this:

RegAsm : error RA0000 : Unable to locate input assembly 'G:\Anshul\Software Set-ups\Tech Hacks\EverythingToolbar-master\EverythingToolbar\tools\..\bin\Release\EverythingToolbar.dll' or one of its dependencies.

Please Help

**Comment by stnkl** [comment]
You accidentally downloaded the source code rather than the compiled program. Please go to the [releases ](https://github.com/stnkl/EverythingToolbar/releases) page and download the msi-installer from there.
