### ISSUE TITLE
icon on taskbar with no text field.

### ISSUE THREAD

**Issue by rydor85** [stnkl/EverythingToolbar#13]
Not sure what could have gone wrong here. I tried to use the prebuilt and built it myself, same result. magnifying glass with no text field on the far right by systray.

win10 20H2

**Comment by stnkl** [comment]
The magnifying glass icon is actually [just a unicode symbol](https://github.com/stnkl/EverythingToolbar/blob/fabd9d6841a2cac744ea7dcca3b84d1e1b782cec/EverythingToolbar/ToolbarControl.xaml#L28). I should change it to a proper vector image in the future. Can you unlock your taskbar (right click on empty space of taskbar) and resize the toolbar to show the rest of the input box?

**Comment by rydor85** [comment]
I can not say for sure WHY, but now I have an expansion widget next to the search field. 

This resize controller was not present at the time of my issue report and the same file was used to generate the search bar.

(Input: if possible in band settings make the default generated text input field size a function of percentage?)

**Comment by stnkl** [comment]
> This resize controller was not present at the time of my issue report and the same file was used to generate the search bar.

Maybe your taskbar was not actually unlocked?

> (Input: if possible in band settings make the default generated text input field size a function of percentage?)

I will improve the default search bar width when I get around to implementing the icon-only mode (like Windows 10 search has).

**Comment by rydor85** [comment]
I think you are correct, my build of windows is a bit.... experimental right now. My thought is that since my install was fresh and things were being moved around a lot the setting itself was stuck locked even though it indicated otherwise. 

I did perform a fresh boot and re-setting/unsetting of the lock tick between tries.

Thanks for the work so far works great.

**Comment by stnkl** [comment]
Actually now that you say it, if there is no other toolbar enabled the taskbar appears locked even though it actually is unlocked (just tested that). So the problem was rather that you couldn't enable/hadn't enabled EverythingToolbar for some reason.

**Comment by rydor85** [comment]
Well that is a strange one perhaps with the delay behavior of the refresh of toolbar option in context menu after running the installer there was something not quite ready at the time the resource was called into existence.
