### ISSUE TITLE
Cant see this at toolbar option 

### ISSUE THREAD

**Issue by SamKur** [stnkl/EverythingToolbar#130]
i think this is  a bug. Cant see this at toolbar option . tried installing - reinstalling.

**Comment by stnkl** [comment]
Did you open the context menu twice? It doesn't show up the first time. You have to open the context menu at least twice for the EverythingToolbar menu entry to show up.

**Comment by Shaishav23** [comment]
I tried opening context meenu twice still it's not showing.

**Comment by stnkl** [comment]
Which version of EverythingToolbar did you install?

**Comment by karticchaudhary** [comment]
Version - 1.4.1.1005(x64)

**Comment by stnkl** [comment]
> Version - 1.4.1.1005(x64)

I think you only installed [Everything](https://www.voidtools.com) but you also need to install [EverythingToolbar](https://github.com/stnkl/EverythingToolbar/releases/tag/0.6.3) which are - despite the similar name - two separate applications. Everything is the file search engine while EverythingToolbar is only a small application to make those search results available from within the Windows taskbar.

Recently there has been some confusion regarding that and I will try to make it clearer in the future.

So after installing EverythingToolbar you should be able to enable it. Let me know if it worked for you!

**Comment by karticchaudhary** [comment]
I feel so stupid right now.
Thanks btw.
