### ISSUE TITLE
Can't able to enable the Toolbar for some reason

### ISSUE THREAD

**Issue by ZubyanUwU** [stnkl/EverythingToolbar#131]
Okay, so i did an oopsie I installed the toolbar before installing the 'Everything' program but I have uninstalled both of them and tried installing the program first and then the toolbar it is appearing in the taskbar but doesn't seem to activate. I can enable other Windows toolbar just fine

**Comment by stnkl** [comment]
This is likely issue #120. Could you please uninstall version 0.6.2 and try [0.6.3](https://github.com/stnkl/EverythingToolbar/issues/120#issuecomment-808812143) instead?

**Comment by ZubyanUwU** [comment]
That worked flawlessly, thank you so much for your instant response.

**Comment by stnkl** [comment]
Thanks for the feedback!
