### ISSUE TITLE
[Suggestion] Can you make toolbar pop up whenever i type something in Startmenu

### ISSUE THREAD

**Issue by ZubyanUwU** [stnkl/EverythingToolbar#132]
Hey mate, so I have this weird muscle memory I simply press the start menu button and start typing because I know it's same as clicking the search button. I would really appreciate it if you can do that, though I am not sure if it's possible.

**Comment by stnkl** [comment]
Thanks for the suggestion! This has been requested/discussed before in #63. There is currently a (rather hacky) way to accomplish that by using an [AutoHotkey script](https://github.com/stnkl/EverythingToolbar/issues/63#issuecomment-772733328). I might properly add this functionality in the future.

I'm closing this issue as it is a duplicate.
