### ISSUE TITLE
Reduced or resizeable search results window.

### ISSUE THREAD

**Issue by Jpobi** [stnkl/EverythingToolbar#140]
**Is your feature request related to a problem? Please describe.**
The current window size when doing a search is a tad too big for comfort on smaller screen devices.

**Describe the solution you'd like**
To be able to select between several window sizes or making it resizeable by the user would easily solve this.

**Additional context**

Regular Windows search tool VS Everything Toolbar's size comparison:

Windows:
![image](https://user-images.githubusercontent.com/48343177/114475663-0f2bdb00-9bcf-11eb-8f61-38a7ac19fa80.png)

Everything Toolbar:
![image](https://user-images.githubusercontent.com/48343177/114475566-e73c7780-9bce-11eb-9519-cb4d1331e9d1.png)

The difference might not be that big, but it certainly gets in the way of using whatever is behind.

**Comment by stnkl** [comment]
You can actually already resize the window by grabbing one of the corners!

**Comment by Jpobi** [comment]
Thank you! My bad.
