### ISSUE TITLE
IME is always on

### ISSUE THREAD

**Issue by AioiLight** [stnkl/EverythingToolbar#141]
**Describe the bug**
IME (Input Method Editor) is always on when opening Everything Toolbar.

**Steps to reproduce**
1. Open Everything Toolbar.
2. Reproduced (I checked on Microsoft IME (Japanese), and ATOK IME (Japanese))

**Expected behavior**
In general applications, IME keeps the previous IME state.
When you search without using the IME, it will remain off the next time you search.
And, when you search with using the IME, it will remain on the next time you search.

Removing the code added in 50d5fd0 or chage `InputMethodState.On` to `InputMethodState.DoNotCare`, will fix this bug.
But as shown in #58, the problem may recur with IME in other languages.

I tried using Pinyin and it seems to work without the code on line 14 (Ctrl + Space to switch between inputs).

**Screenshots**

Look icon of taskbar. Icon always switched to "あ" when opening. ("あ" means IME turned on)

https://user-images.githubusercontent.com/13918537/114577144-bcc5e980-9cb6-11eb-929a-482dfeafdf25.mp4

Below is removing line 14. IME keeps the previous IME state.

https://user-images.githubusercontent.com/13918537/114581416-a7eb5500-9cba-11eb-82cf-ac90868cd6f2.mp4

**Log file output**

<details>
<summary>Log output</summary>

```
2021-04-13 23:47:41.5389|INFO|EverythingToolbar started. Version: 0.6.3.0, OS: Microsoft Windows NT 10.0.19042.0|

```
</details>

**Comment by stnkl** [comment]
Thanks for the in-depth bug report! I don't completely remember the details of #58. I will look into it in a few weeks as I am quite busy currently.

If you feel like your fix works for Japanese and Chinese input feel free to draft a PR and I will do some more testing then. 😊

**Comment by AioiLight** [comment]
I can make the PR easily because changing code is little, but I think it is necessary to test this carefully because the impact is big in environments where IME is used.

**Comment by stnkl** [comment]
I tested your change with Chinese IME and it worked fine for me! I merged your PR and therefore I'm closing this issue now.
