### ISSUE TITLE
"No files were found" message

### ISSUE THREAD

**Issue by LuigiImVector** [stnkl/EverythingToolbar#144]
I've noticed that searching for something that isn't on the computer brings up a blank screen instead which can be confused with a loading screen, I propose adding a simple text warning if no files were found.
![2021-04-15 18-37-10](https://user-images.githubusercontent.com/59611597/114906953-df711300-9e1a-11eb-8126-b40410dbd771.gif)

**Comment by Horst12** [comment]
Such a message would be useless as you can always type on or modifying your input to get results
and the toolbar doesn't know that you are finished.

**Comment by LuigiImVector** [comment]
Shows the message only when you do not write for more than a second

**Comment by stnkl** [comment]
Could be combined with #97.

**Comment by Horst12** [comment]
> 
> 
> Shows the message only when you do not write for more than a second

That would not be enough to think about my input and what to change.

**Comment by stnkl** [comment]
I added an option to display the number of search results:

![grafik](https://user-images.githubusercontent.com/17520641/121089793-f105e400-c7e7-11eb-87fa-b918fd33f267.png)

It will be available in the next release.
