### ISSUE TITLE
Add support for multiple themes

### ISSUE THREAD

**Issue by YamatoRyou** [stnkl/EverythingToolbar#147]
Refined issue text
------------------
Currently, styles of the individual components are tightly integrated into their respective implementation, making it hard to switch styles easily. Especially considering the fact that future design iterations will come with each major version of Windows, having the ability to apply different styles to each component would be beneficial. This would require decoupling the styles from the components and storing them in a separate resource dictionary. Later on the theme will be selected automatically based on the Windows version used or manually by overriding a setting. Potentially the user would be able to write their own resource dictionary to allow further customization as requested in some of the linked issues below.

Original issue text
-------------------
Operating system: 64-bit Windows 7
Although the height of the toolbar is exactly the same as the height of the taskbar, the toolbar will cover the divider, making it appear higher than the taskbar (approximately 1~2 pixels).
![{60EFAFD7-1666-BF85-B5CF-F4D7277A2BC9}](https://user-images.githubusercontent.com/48104960/115122021-54de0e80-9fe8-11eb-8286-d7ba60de948c.png)

**Comment by Horst12** [comment]
Here under Windows 10 x64 I don't see a problem.
![Screenshot - 17 04 2021 , 21_44_40](https://user-images.githubusercontent.com/38587340/115125103-55fe4400-9fc6-11eb-8c29-9a2742e300b8.png)

**Comment by stnkl** [comment]
Currently there is no way to do that. You can however try changing the [search box border](https://github.com/stnkl/EverythingToolbar/blob/d316efeceb73208a40164d28e05cb043423e77a1/EverythingToolbar/Themes/Light.xaml#L12) to full transparency (#00000000) as a temporary way to visually slim it down by one pixel on each side. The theme files can be found in the installation directory of EverythingToolbar.

I might expose more styles for theming in the future to allow such customization though.

**Comment by stnkl** [comment]
Most of the styles are now exposed as xaml files in the installation directory and can be changed. This way it is possible to completely change the appearance of EverythingToolbar. This should fulfill all the requirements in the linked issues.

https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0

**Comment by ragundo** [comment]
Hi there

I come from #119 
I searched in the xaml files for setting the font name. You can only change the font size, but not the font name.

Is it possible to change the font?

Terrific tool by the way. I've installed in all my computers.

**Comment by srwi** [comment]
> Is it possible to change the font?

You can just set a new [FontFamily property](https://learn.microsoft.com/de-de/dotnet/api/system.windows.media.fontfamily?view=netframework-4.7.2) on the ContentControl element to change the font.
