### ISSUE TITLE
Sometimes the input method cannot be displayed (Chinese input method)

### ISSUE THREAD

**Issue by YamatoRyou** [stnkl/EverythingToolbar#148]
Sometimes the input method cannot be displayed (Chinese input method)

Operating system: 64-bit Windows 7
Toolbar version: 0.6.3
Input method: Sogou Pinyin 7.1; Rime 0.14.3

When focusing on the search box and trying to enter Chinese characters, the input method editing status is sometimes invisible or flickering. Flickering usually appears when the search results pop up.
The particularity of this error makes it impossible to display it directly through screenshots.

**Comment by stnkl** [comment]
Hi, unfortunately I will not be able to fix this issue as Windows 7's support has ended and I don't have any Windows 7 installation. As far as I know this is not an issue on Windows 10.
