### ISSUE TITLE
Toolbar won't stay activated after restart of pc

### ISSUE THREAD

**Issue by Stimmenhotel** [stnkl/EverythingToolbar#151]
**Describe the bug**
I had no problems installing the toolbar. With 6.3 it even shows up on first right-click.
Once I activate the toolbar, it shows up, I can resize and move it.
Searching working too.

But once I restart my PC the icon is gone, and I need to activate the toolbar again.
The settings seem to be saved correctly (theme and details-mode).

I have already tried an uninstallation and can't find any leftover files. Don't know about registry entries.

Is there something harmful [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns) can do to the toolbar? Because I deleted/deactivated some empty/unknown entries, but none directly had anything to do with the toolbar.
Using the task manager autostart I have found one only called "Program" which had no path to open and I used autostarts to delete the entry.

**Steps to reproduce**
1. Install
2. Activate
3. Restart
4. Search bar is missing

**Expected behavior**
Showing the search bar like it was before restart.

**Log file output**
<details>
<summary>Log output</summary>

```
2021-04-24 11:39:15.7314|INFO|EverythingToolbar started. Version: 0.6.3.0, OS: Microsoft Windows NT 10.0.19042.0|
2021-04-24 11:39:16.1689|INFO|Everything version: 1.4.1|
2021-04-24 11:41:04.8052|INFO|EverythingToolbar started. Version: 0.6.3.0, OS: Microsoft Windows NT 10.0.19042.0|
2021-04-24 11:41:05.4459|ERROR|IPC is not available.|
2021-04-24 11:41:05.4459|ERROR|Failed to get Everything version number. Is Everything running?|
```
</details>

**Comment by stnkl** [comment]
Hi! How long did you have the toolbar enabled before rebooting? Windows seems to only remember changes to toolbar states after they have been enabled for a few minutes (or hours?). I can't give you any exact numbers but maybe just try to leave it enabled as you're using the computer and see if it is still missing after the next reboot.

I can reproduce your problem when rebooting right after enabling it but I don't think there is anything I can do about that.

**Comment by Stimmenhotel** [comment]
Good question ... for testing of course not long.
I will use the PC now for a few hours and will test again.

Sadly I can't say when this occurred the first time... So I can't precisely say what I did before. The cleaning of autostarts was the "biggest" thing I did for a while.

**Comment by stnkl** [comment]
I don't think the other stuff you did has anything to do with it.

I just tried this with other Windows toolbars (Desktop, Links, Address, etc.) and they show the same behaviour.

**Comment by Stimmenhotel** [comment]
After 3 hours and a restart the toolbar disappears again

**Comment by stnkl** [comment]
Could you please try this again with any of the other toolbars that come with Windows?

**Comment by Stimmenhotel** [comment]
Tried it today with "address" and after around 2h I have restarted my PC. The toolbar is missing again. So it is at windows fault somehow not saving toolbar states.

But to fixate state is saved. (the ability to move/resize items)

**Comment by stnkl** [comment]
Hi, were you able to solve this problem? I would like to close this issue as it seems to be unrelated to EverythingToolbar.

**Comment by Stimmenhotel** [comment]
Sorry for not answering on time. But I haven't resolved this issue yet... But as you said it is a problem with the local windows installation (hopefully) and once I reinstall it, and the problem remains, I can reopen the issue.(don't think so, since it was working before)

**Comment by stnkl** [comment]
Yes, please let me know if the problem persists after reinstalling Windows!

**Comment by Onyvox** [comment]
Got the same problem after updating the app from 0.7 to 1.5 version.

**Comment by Horst12** [comment]
> Got the same problem after updating the app from 0.7 to 1.5 version.

Don't joke with us.
The current version of the Toolbar is 1.5.1.0

**Comment by Onyvox** [comment]
> > Got the same problem after updating the app from 0.7 to 1.5 version.
> 
> Don't joke with us. The current version of the Toolbar is 1.5.1.0

Your 'us' may want to check the releases and note that there was a version of 1.5.0 before 1.5.1.0.
The issue still persists after updating even to 1.5.1.0
