### ISSUE TITLE
arm64 windows..

### ISSUE THREAD

**Issue by pb5050** [stnkl/EverythingToolbar#152]
everything search supports a arm64  
https://www.voidtools.com/Everything-1.4.1.1005.ARM64.zip

anyway u can make this work with taht?

**Comment by stnkl** [comment]
Unfortunately it's not possible at the moment. See #59.

**Comment by pb5050** [comment]
Good news! 

https://www.voidtools.com/forum/viewtopic.php?f=2&t=10039&p=36949#p36949

It might be possible. 

I have an [unofficial SDK](https://www.voidtools.com/Everything.ARM-SDK.zip) for ARM.

I have heard this works with [ES on ARM.](https://www.voidtools.com/es-ARM64.zip)

Could you please let stnkl know.
