### ISSUE TITLE
arm 64 support 

### ISSUE THREAD

**Issue by pb5050** [stnkl/EverythingToolbar#153]
i never got a reply this is what u need you said i think

Good news! 

https://www.voidtools.com/forum/viewtopic.php?f=2&t=10039&p=36949#p36949

It might be possible. 

I have an [unofficial SDK](https://www.voidtools.com/Everything.ARM-SDK.zip) for ARM.

I have heard this works with [ES on ARM.](https://www.voidtools.com/es-ARM64.zip)

Could you please let stnkl know.

**Comment by stnkl** [comment]
For ARM64 support we will have to wait for WPF to support ARM64. Have a look here: https://github.com/dotnet/wpf/issues/1817

**Comment by pb5050** [comment]
> WPF ARM64 support has arrived!
> 
> https://devblogs.microsoft.com/dotnet/net-july-2021/#windows-arm64

**Comment by stnkl** [comment]
Since I do not have an arm device to develop this feature on and there don't seem to be many people interested in this, I will close the issue. Sorry about that,
