### ISSUE TITLE
The search windows always gives two same results.

### ISSUE THREAD

**Issue by 975842069** [stnkl/EverythingToolbar#154]
For example, if I want to seach "abcd.exe", the toolbar will give me two results with the same name "abcd.exe" in the same folder "~/abcd.exe".
      How to solve this problem?
      thx very much!
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Horst12** [comment]
I guess you have added folder indexing in Everything for an NTFS volume
which is indexed already by default.

**Comment by 975842069** [comment]
Hello！&nbsp;In fact， there are three items in everythingtoolbar, "all","files" and "folders". When I am searching for something, first I will see too same results in item "all". If I click item "files", I will see only one result, and then if I come back to &nbsp;the item "all", I will see only one result this time.
&nbsp; &nbsp;I am confused now, if there are some methods to deal with that?
&nbsp; &nbsp;Thx about that!
best




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stnkl/EverythingToolbar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月15日(星期六) 晚上11:23
***@***.***&gt;;
抄送:&nbsp;"Jia ***@***.******@***.***&gt;;
主题:&nbsp;Re: [stnkl/EverythingToolbar] The search windows always gives two same results. (#154)





 
I guess you have added folder indexing in Everything for an NTFS volume
 which is indexed already by default.

**Comment by stnkl** [comment]
Which version of EverythingToolbar are you using? The latest version is 0.6.3.

Does the actual Everything search program (not EverythingToolbar) show different results for the same search query?

**Comment by 975842069** [comment]
The actual&nbsp; Everything search program works well，I will only get one result.
I am using version 0.5.2.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stnkl/EverythingToolbar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 凌晨0:32
***@***.***&gt;;
抄送:&nbsp;"Jia ***@***.******@***.***&gt;;
主题:&nbsp;Re: [stnkl/EverythingToolbar] The search windows always gives two same results. (#154)





 
Which version of EverythingToolbar are you using? The latest version is 0.6.3.
 
Does the actual Everything search program (not EverythingToolbar) show different results for the same search query?

**Comment by stnkl** [comment]
Duplicate search results (#43) have been fixed in version 0.6.0. Please uninstall version 0.5.2 by running `uninstall.cmd` and install the latest version:

https://github.com/stnkl/EverythingToolbar/releases/tag/0.6.3

**Comment by 975842069** [comment]
wow! thanks so much!
GOOD JOB!
THX!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stnkl/EverythingToolbar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 凌晨1:13
***@***.***&gt;;
抄送:&nbsp;"Jia ***@***.******@***.***&gt;;
主题:&nbsp;Re: [stnkl/EverythingToolbar] The search windows always gives two same results. (#154)





 
Duplicate search results (#43) have been fixed in version 0.6.0. Please uninstall version 0.5.2 by running uninstall.cmd and install the latest version:
 
https://github.com/stnkl/EverythingToolbar/releases/tag/0.6.3
