### ISSUE TITLE
Changed settings always restored after several reboots

### ISSUE THREAD

**Issue by Walkerby** [stnkl/EverythingToolbar#155]
**Describe the bug**
Changed settings always restored after several times reboot.
The log says '|ERROR|IPC is not available.||Failed to get Everything version number. Is Everything running?'. But the everything toobar is actually usable and everything is runing.

**Steps to reproduce**
Describe exactly how to reproduce the behaviour.

**Expected behavior**

**Screenshots**

**Log file output**
Add the log file output from `%TEMP%\EverythingToolbar.log` below.

<details>
<summary>Log output</summary>

```
2021-05-18 18:15:28.7046|ERROR|IPC is not available.|
2021-05-18 18:15:28.7046|ERROR|Failed to get Everything version number. Is Everything running?|

```
</details>

**Comment by GDT1978** [comment]
I have the same issue.

**Comment by stnkl** [comment]
Can you please describe in more detail how to reproduce this? The bug description is very vague.

**Comment by GDT1978** [comment]
I have Everything toolbar installed about 3 months ago on 2 PCs and I setted it with dark theme, sort by launch counter and hide empty search. I noticed that randomly after reboot I lost my settings, this happens on both my PCs so I searched for a listed issue and saw Walkerby's one.
I can confirm I have the same entries into the log file.

**Comment by stnkl** [comment]
Thanks. I've had it set up just like you for a few days now and couldn't reproduce the issue thus far.
If anybody has exact steps to reproduce the issue consistently please let me know.

**Comment by GDT1978** [comment]
It happened to me about 4 times since installed.

**Comment by stnkl** [comment]
It happened to me yesterday. It looks like this happens when explorer.exe gets updated via a Windows update. If you look at `%LOCALAPPDATA%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj` there should be several folders named after the explorer.exe version containing your current and old configurations for EverythingToolbar.

I'll look into fixing this.
