### ISSUE TITLE
Open search in full everything instance

### ISSUE THREAD

**Issue by leehadassin** [stnkl/EverythingToolbar#16]
Love the project. Just a small suggestion - a button or way to open the current search in a full everything instance.

**Comment by stnkl** [comment]
Thanks! This feature is already planned and will be in the next release. I need a little while though as I'm currently busy with other things.

**Comment by leehadassin** [comment]
> Thanks! This feature is already planned and will be in the next release. I need a little while though as I'm currently busy with other things.

Legend! Thanks for a great project!

**Comment by stnkl** [comment]
In today's (pre)release you can now press Shift+Enter within the search box to open the current search within a full Everything instance!
