### ISSUE TITLE
Support basic search macros

### ISSUE THREAD

**Issue by DennisKassel** [stnkl/EverythingToolbar#162]
**Describe the bug**
When I try to search for certain media files like audio or video by typing in the condition, there aren't any search results. If I press multiple times the Tab key to set the filter manually, it works.

**Steps to reproduce**
1. Launch Everything Toolbar
2. Type in "audio:" or "video:"

**Expected behavior**
Everything Toolbar should display the same search results as Everything.

**Screenshots**
```

**Log file output**
While these steps happen, a log file won't be created.

<details>
<summary>Log output</summary>

```
Replace this line with the log file output.
```
</details>

**Comment by stnkl** [comment]
Hi Dennis. Unfortunately macros like `audio:` or `video:` are not supported by the Everything SDK yet. But I could work around this by replacing `audio:` with the corresponding file endings `ext:mp3;aac;...` in code behind so it effectively does the same as switching filters via the tabs.

**Comment by DennisKassel** [comment]
> Hi Dennis. Unfortunately macros like `audio:` or `video:` are not supported by the Everything SDK yet. But I could work around this by replacing `audio:` with the corresponding file endings `ext:mp3;aac;...` in code behind so it effectively does the same as switching filters via the tabs.

Hi stnkl,

this would be absolutely amazing. I don't like it to press multiple times Tab to filter my search results. It would much easier to just type it in. And I think, it wouldn't take a huge effort to implement this.

**Comment by stnkl** [comment]
Indeed it was very easy to implement and will be available in the next beta release (probably within the next week or two). 😊
