### ISSUE TITLE
Increase ⁝ menu spaces and rearrange nested menus

### ISSUE THREAD

**Issue by iJahangard** [stnkl/EverythingToolbar#163]
It such a pain , any time i want do something like switch themes , i face to nested menus (absolutely with a Low height menu type i hope you add ablity to set height of menus in theme script)
It can be more accessible

Also that part of it's UI needs more beauty 
Thanks in advance

**Comment by stnkl** [comment]
Could you please describe the problem in more detail?

**Comment by Horst12** [comment]
How often do you need anything from preferences
which btw displays fine here.
After the setup I almost never need this again.

**Comment by iJahangard** [comment]
> Could you please describe the problem in more detail?
> 
> Edit: Got it now.

I do some theming for tha app and the way menus look like, I sucks my nerves
Absolutely i can restart explorer for make things take effect, but hey I need to back to the theme folder and other some times


About height of menus under three dot :
In touch expensive and in high resolution displays menus look small
Make them hrighter will make them easy to access and more beautiful

**Comment by iJahangard** [comment]
Or wait 
Maybe add a restart button in three dot menu will solve the problem

**Comment by stnkl** [comment]
In the next beta the settings menu will be more in line with the windows search settings menu:

![grafik](https://user-images.githubusercontent.com/17520641/123828540-e24fb000-d901-11eb-9a63-0ddf83253f27.png)

Currently I don't see a need to rearrange the menu. At some point a dedicated settings screen can be added as suggested in #109 to make navigation a little easier.

**Comment by iJahangard** [comment]
> In the next beta the settings menu will be more in line with the windows search settings menu:
> 
> ![grafik](https://user-images.githubusercontent.com/17520641/123828540-e24fb000-d901-11eb-9a63-0ddf83253f27.png)
> 
This looks pretty cool , better than pervious design!
> Currently I don't see a need to rearrange the menu. At some point a dedicated settings screen can be added as suggested in #109 to make navigation a little easier.
> for me ! Switching themes are a bad experience
It is fine if move themes menu toto first menu

**Comment by stnkl** [comment]
Okay, I will move the view and theme menus up one level. Thanks for the feedback!

**Comment by iJahangard** [comment]
Thank you for responding !
