### ISSUE TITLE
In app exclude list

### ISSUE THREAD

**Issue by iJahangard** [stnkl/EverythingToolbar#164]
I need to select my exclude folders in app

Because i see a lot of things in search results
But i want them in everything

**Comment by Horst12** [comment]
You have the full Everything syntax available in the Toolbar.
This includes the function to exclude things from the results.
Simple Example
search_for_this !but_exlude_this

**Comment by stnkl** [comment]
@iJahangard You would then use @Horst12's method like this to create a custom filter (enable "Use Everything filters" in EverythingToolbar settings):

![grafik](https://user-images.githubusercontent.com/17520641/122395323-24c6d380-cf77-11eb-9570-42703447fd39.png)
