### ISSUE TITLE
Add a custom path to search as a tab

### ISSUE THREAD

**Issue by iJahangard** [stnkl/EverythingToolbar#166]
I have some hard drives that i store many things in them
Most of times i need to search in them immediately but there is no tool for that

I hope you add this ability to your amazing application

Thanks in advance

**Comment by Horst12** [comment]
You have to configure your drives in Everything.
The Toolbar is only the way to query what is stored in Everything

**Comment by stnkl** [comment]
You can create custom filters within Everything and use those in EverythingToolbar by checking "Use Everything filters" in the settings menu. You can then select those filters in the dropdown menu or navigate to them by pressing <kbd>Tab</kbd> or <kbd>Shift</kbd>+<kbd>Tab</kbd>.

![grafik](https://user-images.githubusercontent.com/17520641/122272880-22b23580-cee1-11eb-9f99-f83e15b2ba8e.png)

This is the corresponding filter configuration:

![grafik](https://user-images.githubusercontent.com/17520641/122273158-69079480-cee1-11eb-8c4d-2e326a7dd397.png)

**Comment by Horst12** [comment]
> 
> 
> You can create custom filters within Everything and use those in EverythingToolbar by checking "Use Everything filters" in the settings menu. You can then select those filters in the dropdown menu or navigate to them by pressing Tab or Shift+Tab.
> 
> 
Unfortunately this is currently not compatible with Everything 1.5

**Comment by stnkl** [comment]
> Unfortunately this is currently not compatible with Everything 1.5

I didn't really have a look at 1.5 yet as I'm guessing most people use the stable release. I'll look into that when 1.5 gets closer to release.

**Comment by stnkl** [comment]
> Unfortunately this is currently not compatible with Everything 1.5

I didn't really have a look at 1.5 yet as I'm guessing most people use the stable release. I'll look into that when 1.5 gets closer to release.

@iJahangard To answer the original question specifically you would set it up like this:

![grafik](https://user-images.githubusercontent.com/17520641/122394173-f5639700-cf75-11eb-9f74-b1856b6abf9b.png)

This searches only within drive `D:` and `E:`. More drives can be added by separating them with `|`.
