### ISSUE TITLE
Search macro replacements incorrect when using Everything filters

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#169]
Simple functions are no longer working.
Examples:
I have a folder test2 which is found and shown as long as I have **All** in the Toobar
If I switch to **Folder** in the Toolbar nothing is shown.
Nothing is found if I use basic Everything functions like file: or folder: whatever I enter after it.
In the previous version I could type folder:test2 and it was found of course.
Example **size:>1gb** doesn't found anything in the Toolbar and a lot in the Everything GUI.
In fact all Everything functions are lost and I can only enter simple text to search.

**Comment by Horst12** [comment]
I found the simple reason 
For the previous version I had to point the Toolbar to an old version of Everything filters.
Now it needs the actual filter.csv from my Everyting 1.5 Alpha version.

**Comment by stnkl** [comment]
Would it be possible for you to post the problematic filters.csv and config file here so I can reproduce the behavior? The config file is located at `%LOCALAPPDATA%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\<latest-version-number>\user.config`. Also is there any interesting output in the log file? Thanks!

**Comment by Horst12** [comment]
Yes, here are the old and the actual filters.csv
The old one came from my previous Everything 1.4 installation.

[Filters.zip](https://github.com/stnkl/EverythingToolbar/files/6696209/Filters.zip)

**Comment by Horst12** [comment]
And her the actcual config file
[user.zip](https://github.com/stnkl/EverythingToolbar/files/6696224/user.zip)

**Comment by stnkl** [comment]
Thanks! This will be fixed in the next release.

**Comment by Horst12** [comment]
I have disabled filters for now.
