### ISSUE TITLE
Open Path follows Everything configuration

### ISSUE THREAD

**Issue by berlihingen** [stnkl/EverythingToolbar#17]
If it would possible to follow the Everything config on "Open Path" – Ctrl+Enter opens a path in Total Commander (in my config). I use this command more often than Run (Enter) and I don't use MS file Explorer. Thanks.

**Comment by Darthagnon** [comment]
I, too, would appreciate more "Open Path" options, as that is how I typically use Everything (rarely use it for running/opening directly). Or maybe a settings checkbox to enable Open Path when a result is clicked, rather than running the result?
