### ISSUE TITLE
Terminated all my Chrome windows

### ISSUE THREAD

**Issue by anonimuos** [stnkl/EverythingToolbar#171]
The new version 0.7.0.0 beta 1 of Everything Toolbar is simply fantastic. So many enhancements. Especially love the icons for filters, show results count, quick toggles, keyboard navigation of results, macros like ext:, video:.

THANK YOU!!

One thing I noticed when installing over older version (even though I had "Exit Explorer" from the taskbar) and Voidtools Everything is that it terminated my Chrome browser windows. Is that supposed to happen? I could recover all the tabs and windows but just thought I'd let you know it did that.

Does the installer use any feature of Windows Installer (MSI) like Restart Manager that automatically closes in-use apps or something? Maybe that caused Chrome to get terminated. It didn't show me any warning or option to close it. It just straight up terminated it.

**Comment by stnkl** [comment]
Thank you for the kind words!

Unfortunately I can't reproduce that. Chrome does not get terminated for me when upgrading from 0.6.3 to 0.7.0-beta1. It even gets restarted after rebooting (when selecting "yes" in the reboot dialog).

Are you able to reproduce it yourself by installing 0.6.3 again and upgrading?

**Comment by anonimuos** [comment]
Well maybe it crashed at the exact same time as I was exiting Explorer. Will report if it happens again.

**Comment by anonimuos** [comment]
Updated to 0.7.0-beta 2. Chrome didn't close so it must was due to something else. Not related to your excellent toolbar.

**Comment by stnkl** [comment]
Thanks for reporting back! 🙂
