### ISSUE TITLE
display path column for results

### ISSUE THREAD

**Issue by rgbigel** [stnkl/EverythingToolbar#173]
Looking for a file or folder with duplicate names in different locations gives results which are somewhat meaningless, if the path is not given. 
Please add a column giving path of the result items.

**Comment by Horst12** [comment]
Thats done by using one of the detailed views.

**Comment by rgbigel** [comment]
Newbees... Wer sucht, der findet. 
A little help function would help, still looking for the function keys that I saw somewhere. I'm gonna find them...

**Comment by Horst12** [comment]
> 
> 
> Newbees... Wer sucht, der findet.
> A little help function would help, still looking for the function keys that I saw somewhere. I'm gonna find them...

From the Readme.md

Keyboard shortcuts
| Shortcut | Function |
|——————————————————-|————————————–|
| ↑/↓ | Navigate search results |
| Ctrl+↑/↓ | Navigate search history (if enabled) |
| Return | Open |
| Ctrl+Return/Click | Open path |
| Shift+Return/Click | Open in Everything |
| Alt+Return/Click | File properties |
| Ctrl+Shift+Enter | Run as admin |
| (Shift+)Tab | Cycle through filters |
| Ctrl+0-9 | Select filter |
| Ctrl+Space | Preview file in QuickLook |
| Win+Alt+S | Focus search box (customizable) |
