### ISSUE TITLE
Replace Start search bugs

### ISSUE THREAD

**Issue by anonimuos** [stnkl/EverythingToolbar#174]
On one PC running Windows 10 21H2, Replace Start search worked. Of course I had to disable Open Shell and StartIsBack++ (which I used for theming the taskbar).

On another PC running Windows 10 1803, it didn't work even though both were disabled.

Also Win+S which opens Windows search, types S into Everything Toolbar.

**Comment by stnkl** [comment]
Thanks. It has been fixed for the next release.

**Comment by anonimuos** [comment]
Works!! Very reliably now! Even with any Start menu replacements running!! Awesome! Also faced no issues of Chrome being terminated.
