### ISSUE TITLE
Shortcut resets to default automatically

### ISSUE THREAD

**Issue by orchidalloy** [stnkl/EverythingToolbar#179]
Twice now, randomly (either after a windows update, restarting, or some indeterminate amount of time) the Shortcut preference gets reset to Win+Alt+S even though I've manually set it to Win+S twice. Do you have an idea of how this could happen?

<details>
<summary>Log output</summary>

```
2021-06-25 20:49:13.5869|INFO|EverythingToolbar started. Version: 0.6.2.1, OS: Microsoft Windows NT 10.0.19042.0|
2021-06-25 20:49:13.7714|INFO|Everything version: 1.4.1|
```
</details>

**Comment by stnkl** [comment]
Are you running the latest version 0.7.0-beta2? Your log file seems to be an old one from version 0.6.2. But I don't think you should have even been able to set it to Win+S on 0.6.2 anyways.

**Comment by orchidalloy** [comment]
I see, thanks.

I was setting it to Win+S by temporarily disabling Win+S shortcuts in registry

**Comment by stnkl** [comment]
Clever workaround!
