### ISSUE TITLE
Keyboard shortcut/macro?

### ISSUE THREAD

**Issue by crodriguezouterelo** [stnkl/EverythingToolbar#18]
Hi! I've been using Everything for years now, but I've just found out about this project. Love it so far! I have a question though: is it possible to use/call it through a keyboard shortcut? I've always mapped Everything to a function key, and I'm wondering if I could do the same but using this toolbar instead (so I don't have to close Everything's window afterwards).

**Comment by stnkl** [comment]
Thank you! It's not possible at the moment but planned for a future release. I'll close this issue now as it is a duplicate of #10.

**Comment by crodriguezouterelo** [comment]
Whoops... Did not see that. Well, I'll be expecting that update. Thanks for the reply!
