### ISSUE TITLE
Always show Windows taskbar if you're searching something

### ISSUE THREAD

**Issue by dag7dev** [stnkl/EverythingToolbar#181]
When using W10 and selecting the option "hide automatically toolbar, if you're not focusing", if you manage to search something on EverythingToolbar, the bar hides.

It would be nice to kinda "send an intent" to taskbar, in order to "fake" its focus, because is really annoying that taskbar continues to hide and EverythingToolbar search windows remains detachable.

Examples with vs without focus on taskbar:
![withfocus](https://user-images.githubusercontent.com/44711271/124264002-448ff700-db34-11eb-90d1-583ee9c2815f.png)
![withoutfocus](https://user-images.githubusercontent.com/44711271/124263892-20ccb100-db34-11eb-9105-674239f1d23b.png)

What I mean with autohide:
![immagine](https://user-images.githubusercontent.com/44711271/124264107-5e313e80-db34-11eb-8c22-e75cb19157be.png)

**Comment by stnkl** [comment]
This has been reported in #4 before. There is a workaround but I was not able to make it work yet (see #167).

**Comment by dag7dev** [comment]
My bad :(
