### ISSUE TITLE
Expose the style of the "reduced to icon" search logo (search box disabled)

### ISSUE THREAD

**Issue by NotesOfReality** [stnkl/EverythingToolbar#183]
**Is your feature request related to a problem? Please describe.**
The color/s of the search logo if reduced to icon (search box disabled) cannot be customized, thus making it hardly visible since it's black and my task bar color is transparent black.

**Describe the solution you'd like**
Would you please expose the needed "styles"(?) in the [theme file/s](https://github.com/stnkl/EverythingToolbar/tree/master/EverythingToolbar/Themes) so that I can set the hex value of the color I'd like such icon to be?
I'd obviously love to have 3 customizable values if possible: "normal", "hover", "active".

**Additional context**
![image](https://user-images.githubusercontent.com/11523796/124838866-f93c7500-df87-11eb-836a-58aea4ee9862.png)
![image](https://user-images.githubusercontent.com/11523796/124839072-5fc19300-df88-11eb-8d0a-79b8925c5fca.png)

**Comment by stnkl** [comment]
Which version are you running?

**Comment by NotesOfReality** [comment]
I'm using the version 0.6.3.0 , here's the log [EverythingToolbar.log](https://github.com/stnkl/EverythingToolbar/files/6783346/EverythingToolbar.log)

**Comment by stnkl** [comment]
Thank you! The bug with wrong search icon colors has been fixed in the beta versions of 0.7.0. The latest beta appears to be very stable so you can update to that. 

Other than that I would like to track the rest of this issue under #147. The goal of that is to be able to fully customize every part of EverythingToolbar.

**Comment by NotesOfReality** [comment]
Thank you, I tried to look into the latest beta source code but I failed to recognize this particular issue was fixed.
Sorry for the disturb and thanks for the patience. ❤️

**Comment by stnkl** [comment]
No worries. 🙂
