### ISSUE TITLE
Have applications (.exe) show up first when searching

### ISSUE THREAD

**Issue by fourteen-1** [stnkl/EverythingToolbar#188]
I'm used to using the default windows search to open applications quickly. After binding EToolbar with the windows key, it is difficult to achieve this. Win's default search always always shows applications in the results first. Have applications show up first when searching with the Etoolbar will fix this issue.

**Describe the solution you'd like**
Have an option in the settings to have applications show up first in search results. Giving exe files priority in the search results somehow should achieve this.

**Comment by stnkl** [comment]
Thanks. This has been suggested in #186 before. I just commented on there on how to work around this for now.
