### ISSUE TITLE
Option to choose between file thumbnails or filetype icons

### ISSUE THREAD

**Issue by fhtdtdj** [stnkl/EverythingToolbar#189]
Hi, when searching in any of the 4 viewing modes (similar to Windows explorer details mode), I have thumbnails for images showing instead of the default filetype icon. (not sure if it happens on native Windows thumbnails as I use thumbnail generating software like Icaros)

Whereas in Windows Explorer or Everything standalone, list or details mode only shows filetype icon instead of the actual picture thumbnails; it's useful to immediately identify filetype at a glance when searching through folders full of different filetypes, whereas different tiny thumbnails adds confusion.

Thumbnails should only show when browsing in larger icon modes, or there should be a toggle option.

![001](https://user-images.githubusercontent.com/88416370/129265197-160f1bc0-ce26-41ec-9dd7-3e8e51acdae3.JPG)

Could you please also enable persistent text in the search bar? The current text disappears after clicking out of the result window.

**Comment by stnkl** [comment]
Thanks, it will be available in the next release!

**Comment by neoOpus** [comment]
on hover of the thumbnails show a bigger one (on a bubble) maybe? they are too tiny to identify at the actual scale.
