### ISSUE TITLE
Selecting Copy Full Name to Clipboard should hide the toolbar

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#19]
If I select "Copy Full Name to Clipboard" from the context menu
the toolbar stays on screen and I must click somewhere else to dismiss it.

**Comment by Horst12** [comment]
When can we get this in a new release ?

**Comment by srwi** [comment]
There will probably be a release on the weekend. I have to do some stability fixes first and don't have a lot of time to work on the project atm.

<img width="1419" height="788" alt="Image" src="https://github.com/user-attachments/assets/85ba9937-dc47-4f13-a1fa-0b6482a0886d" />
