### ISSUE TITLE
Shortcut To bring up the toolbar resets itself.

### ISSUE THREAD

**Issue by DenesHliva** [stnkl/EverythingToolbar#191]
**Describe the bug**
I changed the shortcut to bring up the toolbar to ALT + left CTRL + S, and it keeps forgetting i changed it to that, and just reverts to the default shortcut. Maybe its because everything and the toolbar both launch at startup, but thats my only guess.

I cant even change this setting in the .cfg file, and make that file read-only so it cant revert, because i have no clue where these are stored.

**Steps to reproduce**
Usually a computer restart does it.

**Expected behavior**
I change the shortcut and it stays like that.

<details>
<summary>2021-08-16 03:50:35.0065|ERROR|IPC is not available.|</summary>
</details>

**Comment by DenesHliva** [comment]
Edit: Its not consistent though.

I just restarted my computer three times in a row to test it and it didnt reset it. Other than changing this one setting, every time it reverts itself, i dont change the settings, so its unlikely that im fucking this up by making changes constantly.

I wish i knew why it was doing this, so i could help you more.

**Comment by stnkl** [comment]
Which version are you running?

**Comment by DenesHliva** [comment]
0.6.3.0

I'll try updating to latest

**Comment by stnkl** [comment]
That should fix the issue. Somebody else had the same problem in #179.

**Comment by DenesHliva** [comment]
Thanks!
