### ISSUE TITLE
Reduce amount of taskbar space taken up by EverythingToolbar

### ISSUE THREAD

**Issue by Fayyaadh** [stnkl/EverythingToolbar#195]
**Is your feature request related to a problem? Please describe.**

I use a vertical taskbar and the Everything Toolbar takes up quite a bit of vertical real estate, even though the icon itself is sized perfectly, the 'padding' around it is quite large.

**Describe the solution you'd like**

Is it possible to either reduce the amount of taskbar space that is reserved for Everything Toolbar or at least have it somewhat customizable?

**Describe alternatives you've considered**

I want to use Everything Toolbar so I don't want alternatives.

**Additional context**

Screenshot to make it clear.

You can see the actual taskbar icons are much more tightly packed compared to Everything Toolbar's icon.

[Screenshot](https://puu.sh/I5xzP/2263465adb.png)

**Comment by Horst12** [comment]
Starting with Windows 11 there is no longer a vertical taskbar.

**Comment by Fayyaadh** [comment]
But on Windows 10 it's still there.

Is there no way to reduce the padding around the EverythingToolbar icon? Even just a little.

**Comment by stnkl** [comment]
Did you try unlocking the taskbar and resizing EverythingToolbar vertically? It should be possible to reduce its height quite a bit.

**Comment by Fayyaadh** [comment]
> Did you try unlocking the taskbar and resizing EverythingToolbar vertically? It should be possible to reduce its height quite a bit.

Yeah, I've been playing around with it and no matter what I do, I can't seem to reduce it past a certain point.

If you look at my screenshot in the 1st post, you'll see just how massive the padding is around the icon.

**Comment by Fayyaadh** [comment]
Ok, it seems to be sorted now.

Basically, what I did was temporarily change the taskbar to be shown at the bottom like it is by default. Then I resized it and switched back to a vertical taskbar. This got rid of the extra padding.
