### ISSUE TITLE
EverythingToolbar correct install

### ISSUE THREAD

**Issue by AltairVergil** [stnkl/EverythingToolbar#196]
%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /nologo /codebase "%~dp0EverythingToolbar.dll"

**Comment by stnkl** [comment]
You downloaded the source code. Please download the installer from here: https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi

**Comment by AltairVergil** [comment]
After installation  EverythingToolbar-0.7.1.msi  ，  Installation directory  “EverythingToolbar”  is not  install.cmd，

Must be created manually  install.cmd  

input as   %SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /nologo /codebase "%~dp0EverythingToolbar.dll"

to run properly

**Comment by AltairVergil** [comment]
After installation  EverythingToolbar-0.7.1.msi  ，  Installation directory  “EverythingToolbar”  is not  install.cmd，

Must be created manually  install.cmd  

input as   %SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /nologo /codebase "%~dp0EverythingToolbar.dll"

to run properly

**Comment by stnkl** [comment]
You don't have to work with install.cmd at any point. In earlier versions this was the case but for the installer that's not the case anymore. Running the installer is all you need to do.

**Comment by jia-jianhua** [comment]
这个安装之后怎么使用啊

**Comment by stnkl** [comment]
> 
> 
> 这个安装之后怎么使用啊

Have a look at this video: https://user-images.githubusercontent.com/17520641/107118574-19a1bf80-6882-11eb-843a-7e854e5d0684.gif
