### ISSUE TITLE
UI doesn't close when pressing enter on a .lnk file 

### ISSUE THREAD

**Issue by JovialMockingbird** [stnkl/EverythingToolbar#197]
**Describe the bug**
EverythingToolbar window doesn't auto close when I press enter on a .lnk file. 

**Steps to reproduce**
Activate EverythingToolbar via mouse click in the taskbar or by keyboard shortcut -> filename.lnk -> *Enter* -> File opens but EverythingToolbar interface stays active. 

**Expected behavior**
File opens and interface closes like with opening folders, mp3s, exe files, etc. 

**Screenshots**
I can provide a video but I think it should be clear from the description. 

[EverythingToolbar.log](https://github.com/stnkl/EverythingToolbar/files/7087297/EverythingToolbar.log)

**Comment by Horst12** [comment]
Here it works as desired.

**Comment by JovialMockingbird** [comment]
Thanks for trying it out!Ahh I tried it with some new files and that also seems to work for me. Maybe I can describe my specific situation more:

I'm trying to access a shortcut that leads to a specific target for [nircmd](https://www.nirsoft.net/utils/nircmd.html).

In EverythingToolbar:
![image](https://user-images.githubusercontent.com/30690488/131670305-3370089a-46b9-4f81-a67c-6526fb1202a7.png)

The actual file + target:
![image](https://user-images.githubusercontent.com/30690488/131670169-21dfae62-3133-4922-84cb-d33e5e134886.png)

**Comment by stnkl** [comment]
The UI normally only closes when another application acquires focus. Afaik nircmd doesn't have a UI so the EverythingToolbar UI stays visible. I can implement a fix for that!
