### ISSUE TITLE
Integration with Explorer search

### ISSUE THREAD

**Issue by Hunter23071985** [stnkl/EverythingToolbar#202]
Hey!
Thanks for the program!
Please add an integration with [Explorer search](https://uploads.disquscdn.com/images/b8823ec5661ff695d35d45f66ed8d4b7e9a8a47de888932ca2e172145d281605.png?w=800&h=535).

**Comment by Horst12** [comment]
You can enable the redirection of Explorer search (Win S) to the toolbar.
But there is no benefit doing this if you already have disabled the Windows search icon on the taskbar.

**Comment by stnkl** [comment]
I like the idea but this would basically be a completely different application since really nothing from EverythingToolbar can be reused here. I'll close the issue since it's out of scope of this project.
