### ISSUE TITLE
Minimal intercface

### ISSUE THREAD

**Issue by tjhecker** [stnkl/EverythingToolbar#204]
You can make it look good with acrylic blur, home screen with pinned apps and suggested, etc...
it doesn't look good in my opinion I think because I am a interface designer.

**Comment by stnkl** [comment]
> You can make it look good with acrylic blur, home screen with pinned apps and suggested, etc...

Hi! I already thought about acrylic blur but it is not really possible with WPF which is used to create the UI of EverythingToolbar. Also showing pinned apps or suggestions is not the goal of this project. Specifically the goal is to mimic the original Windows search with instant search results without any of Windows' _pseudo-smart_ stuff which I think EverythingToolbar already does quite well.

> it doesn't look good in my opinion I think because I am a interface designer.

If you have specific design suggestions I am happy to change things as long as it's possible to implement with reasonable effort.
