### ISSUE TITLE
Any possibility to support IbEverythingExt?

### ISSUE THREAD

**Issue by okey2k** [stnkl/EverythingToolbar#205]
IbEverythingExt works fine with everything to enable search filename with Pinyin Initials.

It looks not being effective while searching from Everything toolbar.

Any possibility to accommodate it?

thanks.

https://github.com/Chaoses-Ib/IbEverythingExt

![image](https://user-images.githubusercontent.com/32120698/134294823-615a9790-7a21-4017-93e5-8bc52b846c4f.png)

**Comment by Chaoses-Ib** [comment]
It's not EverythingToolbar's fault.  It's that IbEverythingExt v0.2 didn't handle IPC calls, and [v0.3](https://github.com/Chaoses-Ib/IbEverythingExt/releases/tag/v0.3) has added support for that.

**Comment by stnkl** [comment]
Sorry, I don't understand what this is about. Could you please explain the problem in more detail? I don't speak any Chinese and I am not familiar with Pinyin.

**Comment by Chaoses-Ib** [comment]
IbEverythingExt is an extension that enables Everything to search for Chinese characters by Pinyin, like searching for "γ" by "gamma" or "g". In IbEverythingExt v0.2, it didn't handle IPC calls from the Everything SDK, so the Pinyin search function is not available in EverythingToolbar. This is not a matter for EverythingToolbar. And in IbEverythingExt v0.3, this problem has been solved. You can now close this issue.

**Comment by stnkl** [comment]
Thank you for your response!
