### ISSUE TITLE
Search button doesn't close the start menu

### ISSUE THREAD

**Issue by ea-ae** [stnkl/EverythingToolbar#207]
After opening the start menu, click on the Search Everything button. The start menu does not close, but instead stays in the background. The start menu must be separately closed and makes the search function not feel very well-integrated in the toolbar. This is not the case if you click the buttons in a separate order, which is extra unintuitive (the start menu button closes the search window).

[GIF here.](https://i.imgur.com/34VtOz1.gif)

**Comment by stnkl** [comment]
This issue has been addressed in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0).
