### ISSUE TITLE
Option to auto-resize the search popup

### ISSUE THREAD

**Issue by profucius** [stnkl/EverythingToolbar#21]
Request to auto resize the popup search window to the size of the results. If few, window is small to match, if many, fills the screen as large as necessary.

Currently the window only remembers the previous state.

**Comment by Horst12** [comment]
What is bad on remembering the state ?
I set it once to the desired size and it opens in this size for all further invocations

**Comment by profucius** [comment]
I prefer it to match the content, so that it saves the wasted space, and also gives me an idea of how much content I've searched for.

**Comment by Horst12** [comment]
> 
> 
> I prefer it to match the content, so that it saves the wasted space, and also gives me an idea of how much content I've searched for.
I like a fixed frame on which the results are displayed.
What should I see on your wasted space, its on the right side of a large display ?
Your suggestion would be a disadvantage for me if not optional.

**Comment by profucius** [comment]
I'm only proposing this as an option, which could be underneath a settings tab (which the app currently does not have). It is not a crucial necessity, just a preference.

**Comment by stnkl** [comment]
Due to the fact that changing the listviewer size while the opening animation is active causes framedrops (due to item virtualization) I don't think it is a good idea to implement a feature like this.

I'll close this issue for now. If this will be suggested again in the future we can think about a better solution.
