### ISSUE TITLE
Open standard context menu for a search results

### ISSUE THREAD

**Issue by kintrupf** [stnkl/EverythingToolbar#210]
Refined issue text
------------------
Currently EverythingToolbar uses a custom context menu for search result entries. This allows the context menu to be styled to better mimic the Windows 10 search UI. 

![grafik](https://user-images.githubusercontent.com/17520641/193447417-555d7ae1-19bd-431f-ab4c-bcf992572fd7.png)

Other applications can add custom menu entries to the standard context menu in Windows. An example for this would be 7zip's custom menu that supports creating/unpacking archives:

![grafik](https://user-images.githubusercontent.com/17520641/193446814-8e75ffdc-03b2-47c5-8e4d-22c616cc0e2d.png)

Power users of EverythingToolbar might want to use those custom features of the standard context menu from within EverythingToolbar itself so there should be an option in EverythingToolbar to toggle between the styled context menu and the standard context menu. The standard context menu should include entries "Copy path", "Copy Full Name to Clipboard" and "Open in Everything". Additionally it should be possible to open the non-default context menu type by right-clicking a search result entry while holding a modifier key like ctrl or alt.

Original issue text
------------------

It would be great if you could open the standard explorer context menu for a search result.

**Comment by Horst12** [comment]
Make some rule for your importand entries and you will not miss the context menu.

**Comment by claudio-salvio** [comment]
> Make some rule for your importand entries and you will not miss the context menu.

Honestly, I don't understand what you mean.

**Comment by Horst12** [comment]
Look on the docu and the rules under preferences.
You can make rules which allows you to enhance the right click menu in the results
or automatically start apps depending on results type.

**Comment by kintrupf** [comment]
I do have some commands added through rules.
However, this does NOT replace access to the context menu with all the shell extensions and such!
