### ISSUE TITLE
Add support for Everything 1.5 Alpha

### ISSUE THREAD

**Issue by BrianPurgert** [stnkl/EverythingToolbar#214]
Add support for Everything 1.5 Alpha

**Comment by Horst12** [comment]
That works allready.
You simply have to set in your everything-1.5.ini
**alpha_instance=0**

**Comment by joespinoza** [comment]
hi, i install Everything 1.5 Alpha, and I'm using the last version of EverythingToolbar

i already did everithing in [#172](https://github.com/srwi/EverythingToolbar/issues/172) and is not working

[Update]

i fix it
