### ISSUE TITLE
support windows search command like cmd，regedit

### ISSUE THREAD

**Issue by dorahasadream** [stnkl/EverythingToolbar#215]
.
![image](https://user-images.githubusercontent.com/90954998/144564249-383ff1db-b596-4251-a0c4-fceee4518644.png)

**Comment by stnkl** [comment]
I'd say this is outside the scope of this project.

Possible alternatives:
1. You can always start applications by typing in the start menu. 
2. Create a dedicated filter for applications and shortcuts: https://github.com/stnkl/EverythingToolbar/issues/186#issuecomment-890959204
3. Use another launcher like [Wox](https://github.com/Wox-launcher/Wox) which also supports Everything search
