### ISSUE TITLE
Enable using everything instances

### ISSUE THREAD

**Issue by Eric666-tester** [stnkl/EverythingToolbar#216]
Since I strictly use Everything instances, would it be possible to implement those? Currently the Toolbar only responds to an instance-less Everything.

Edit: to my knowledge the instance is determined in the Everything64.dll. Only a small change would be needed here, to support a specific instance (by preference to be configured outside of the dll).

**Comment by stnkl** [comment]
I didn't have a look at the source code of the Everything64.dll yet. This has been asked before so I think more people would like this. Thanks for mentioning a possible implementation!
