### ISSUE TITLE
搜索框中的“用Everything搜索”能否修改

### ISSUE THREAD

**Issue by bestv5** [stnkl/EverythingToolbar#219]
搜索框中的“用Everything搜索”能否修改？如果能，麻烦告知修改方法，如果不能，希望增加配置项。

**Comment by stnkl** [comment]
You can hide the text completely by changing the theme files to have a transparent watermark. To do so change the colors `SearchBoxWatermarkForeground`, `SearchBoxWatermarkForegroundHover` and `SearchBoxWatermarkForegroundActive` to `#00000000` in whatever theme you are using (`Dark.xaml`, `Medium.xaml` or `Light.xaml`). You can find the theme files in the installation folder of EverythingToolbar.

If you want to change the text that is not currently possible. More theming abilities will be tracked in #147.
