### ISSUE TITLE
Search for separate words

### ISSUE THREAD

**Issue by octaviz** [stnkl/EverythingToolbar#22]
In Everything App there is an option to search for several different words, "AND> OR" mode, for example: if I want to search for a phrase that is "I like to drive at night" if I search only for "Drive Night" the results of the complete phrase will come out , I don't know if I explain myself, In the Everything App you can search for different words.

**Comment by Horst12** [comment]
You can use the full Everything serach syntax in the toolbar.
Look under Help / Search Syntax in the Everything GUI

**Comment by octaviz** [comment]
OK, Thanks!!!
