### ISSUE TITLE
Custom Win7 Glass Theme for EverythingToolbar?

### ISSUE THREAD

**Issue by MasterSlenderTR** [stnkl/EverythingToolbar#220]
It'd be pretty good if a glass or aero theme was made for EverythingToolbar because seriously, the toolbar ruins how Win7's aero taskbar looks like. It looks out-of-place.

[Screenshot](https://i.imgur.com/2JZQsKP.png)

**Comment by stnkl** [comment]
There will not be an official Windows 7 theme since it reached EOL a while ago. But in general more theming might come at some point as it is being tracked in #147.

**Comment by MasterSlenderTR** [comment]
"There will not be an official Windows 7 theme since it reached EOL a while ago." There are Win7 ESU updates until 2023 tho

**Comment by stnkl** [comment]
Still #147 is a prerequisite for extended theming. You can add your own themes once it has been implemented.
