### ISSUE TITLE
where is the ShortCut Key setting stored?

### ISSUE THREAD

**Issue by Pendora2017** [stnkl/EverythingToolbar#222]
Hi there,

could anybody answer where the ShortCut Key (WIN + ALT + S) setting is stored?
Maybe registry or some config file?

I know how to change it in the settings but i would like to pre-set it - like proviosoning ;)

**Comment by stnkl** [comment]
It is located in the settings file at `%LOCALAPPDATA%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\<explorer version number>\user.config`.

The keys you are interested in are:

```xml
<setting name="shortcutKey" serializeAs="String">
    <value>62</value>
</setting>
<setting name="shortcutModifiers" serializeAs="String">
    <value>9</value>
</setting>
```

You can look up the values for `shortcutKey` [here](https://docs.microsoft.com/de-de/dotnet/api/system.windows.input.key?view=windowsdesktop-6.0) and for shortcutModifiers [here](https://docs.microsoft.com/de-de/dotnet/api/system.windows.input.modifierkeys?view=windowsdesktop-6.0) (add up the modifier values if you need multiple).

**Comment by Pendora2017** [comment]
Vielen Dank für die schnelle und detaillierte Antwort!!
