### ISSUE TITLE
Compatibility with Everything 1.5 Alpha

### ISSUE THREAD

**Issue by lucaspestana** [stnkl/EverythingToolbar#224]
Hi. Please make EverythingToolbar compatible with [Everything _1.5 Alpha_](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787).

Version 1.5a is set to automatically install to its own separate folder, _C:\Program Files\Everything 1.5a_ (however, I tried installing it on Everything 1.4's own default folder); it is also notable that 1.5a, among numerous other improvements, supports dark mode.

Anyway, EverythingToolbar will fail to work with Everything 1.5a installed.

**Comment by stnkl** [comment]
Please have a look at #172.
