### ISSUE TITLE
Rules are not stored

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#23]
If I define a rule and click on Save the whole desktop refreshes and nothing is saved.
Windows Errro reporting creates an entry starting with:
Version=1
EventType=CLR20r3
EventTime=132498372913561863
ReportType=2
Consent=1
UploadTime=132498372919981625
ReportFlags=524288
ReportStatus=268435456
ReportIdentifier=2b0a9699-9c5d-4c7c-b4d2-1b1e8d824d51
IntegratorReportIdentifier=19aa4967-e999-4ec7-a96b-ba132b54e6a4
Wow64Host=34404
NsAppName=explorer.exe
OriginalFilename=EXPLORER.EXE
AppSessionGuid=00001604-0004-0025-68e8-45b590bad601
TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!000032a63f39de625ba8642545ccfc60f9e3a91dc80f!explorer.exe
TargetAppVer=2061//01//04:21:41:13!47ab23!explorer.exe
BootId=4294967295
TargetAsId=1682
UserImpactVector=269484304
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=ab1e3dc686e0dadb11545792e002b13d
Response.BucketTable=5
Response.LegacyBucketId=1248719285023584573
Response.type=4

**Comment by stnkl** [comment]
Thanks. I just fixed that. Please let me know if beta2 fixes the issue.

**Comment by Horst12** [comment]
Fix confirmed, beta2 works fine so far.
Thanks for the fast fix.
