### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Pixel556** [stnkl/EverythingToolbar#232]
**Describe the bug**
When typing something, it does not work. Even with all the requirements. In the Everything program it too shows nothing.

**Steps to reproduce**
Describe exactly how to reproduce the behaviour.

**Expected behavior**
Expected it was going to work. But no :(

**Screenshots**
![image](https://user-images.githubusercontent.com/95143545/164473140-3ca9d936-d8ad-4b45-9006-7017171398ce.png)

**Comment by Uka-Uka** [comment]
@Pixel556 @srwi Hi, this happens when you uncheck "Run in background" setting in Everything UI section. I've been unchecking this setting since it's located under UI section so I thought this is just meant to hide Everything tray icon.

**Comment by Horst12** [comment]
**The client must be running in the background** to deliver results to other applications.
The setting has nothing to do with showing the tray icon or not.
This can be done with Windows settings.
