### ISSUE TITLE
Double Tap Windows Key for Search with Everything instead of replacing.

### ISSUE THREAD

**Issue by ClassyKM** [stnkl/EverythingToolbar#235]
I'm not sure if it's even possible with how Windows handles the Windows Key, but there are a bunch of things that Windows just handles better but I also want the same convenience of opening it using the same button.

**Comment by stnkl** [comment]
I would advise you to look into something like [AutoHotkey](https://www.autohotkey.com/). With that you can bind double Windows key to whatever shortcut you set EverythingToolbar to trigger on. By default this is Win+Alt+S.
