### ISSUE TITLE
EverythingToolbar keeps hijacking my "backspace" 

### ISSUE THREAD

**Issue by vacarogit** [stnkl/EverythingToolbar#239]
**Describe the bug**
EverythingToolbar keeps hijacking my keystroke "backspace" in a "globle behavior" and start its search box, I don't need that to bother my workflow I only need to activate it by mouse-in the search bar

**Comment by stnkl** [comment]
Hi @vacarogit, could you please send me your configuration file? You can find it at `%LOCALAPPDATA%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\<explorer version number>\user.config`. Please also include the log file at `%LOCALAPPDATA%\Temp\EverythingToolbar.log`.

**Comment by stnkl** [comment]
Hi @vacarogit, would it be possible for you to send me the config and log files so I can have a look at the issue?
