### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by cmdrtigerking** [stnkl/EverythingToolbar#241]
**Describe the bug**

**Steps to reproduce**
Describe exactly how to reproduce the behaviour.

**Expected behavior**

**Screenshots**

**Log file output**
Add the log file output from `%TEMP%\EverythingToolbar.log` below.

<details>
<summary>Log output</summary>

```
Replace this line with the log file output.
```
</details>

**Comment by stnkl** [comment]
Closing until useful information is added.
