### ISSUE TITLE
 0.8.0-beta1 setup assistant not working

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#243]
**Describe the bug**
The setup assistant runs after the installation but nothing of the options in this screen can be selected.

______________________________________________________
Windows 11 Home x64 Version 21H2 (OS Build 22000.795)

**Comment by stnkl** [comment]
The idea is that you have to pin the icon to the taskbar first. Then after it is pinned the other options should be available. Is that not the case for you?

**Comment by Horst12** [comment]
The icon is pinned to the taskbar and I can right click it to start the assistant again.
In the assistant screen the options are shown but nothing can be clicked.
All I can do is closing it with the x on the upper right.

**Comment by stnkl** [comment]
> The icon is pinned to the taskbar and I can right click it to start the assistant again.

I think you are referring to the system tray icon. Instead you have to manually pin the bigger search icon as indicated on the screenshot.

Could you please have a look at the contents of the folder `%APPDATA%\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar` and see if there is a shortcut named `EverythingToolbar` in there?

**Comment by Horst12** [comment]
I tried again and the basic setup is working
but I have StartAllBack installed and want the EverythingToolbar in the taskbar
not only the icon.

**Comment by stnkl** [comment]
It should work with StartAllBack just as it did before. Just don't use the Launcher icon then. Let me know if you are having problems with that.

**Comment by Horst12** [comment]
Ok I found it, just enabled the toolbar in the taskbar as usual.
The pinned icon is not needed for me and I unpinned it.

**Comment by stnkl** [comment]
Cool, I will look out for other feedback regarding the user experience of the setup assistance. But since your problems seem to be resolved I will close the issue. Thank you!
