### ISSUE TITLE
Feature: Some things that would make it fit in with Windows 11 a bit more

### ISSUE THREAD

**Issue by kronuschan** [stnkl/EverythingToolbar#248]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I just built the latest version of EverythingToolbar in Visual Studio, and I love that you are still updating this to work and look good on Windows 11

However, to blend more with the existing flyouts of Windows 11, I have a few suggestions:

1. It would be cool to have Mica, Tabbed, or Acrylic behind the search flyout. I think this relates to #204.
2. Add accent color support to highlighted searches, context menu entries, and the bar under the selected filter.
3. The icons don't fit well with Windows 11's design language; I think it'd be better to use the Fluent design icons that Microsoft uses in Windows 11

These changes, I think, together would help it fit with the rest of the OS and, in turn, make everything feel more coherent.

### Proposed Solution

First, I have limited knowledge about code, and I'm still learning. If anything I'm saying is false or wouldn't work, feel free to ignore it. 
I apologize in advance as I don't know how to implement any of my suggestions; I'll try to give at least some information I found out, though, so it may be easier to implement.

For points 1 and 2:
Mica/blur behind should be possible, there are a few repositories I found that allow adding this, but I've no idea how to adapt it to the toolbar; these are [MicaWPF ](https://github.com/Simnico99/MicaWPF) and [FluentWPF](https://github.com/sourcechord/FluentWPF)
This first library I mentioned here (MicaWPF) also seems capable of handling accent colors, as noted in their examples.

For point 3:
For the icons, using Segoe Fluent Icons instead of Segoe MDL2 Icons would be better on Windows 11, but this font isn't available in Windows 10 by default. I did manage to do this in the code, and I think it does look better.

Also, for point 3:
One thing to note is that I'm using [StartAllBack ](https://www.startallback.com/) to bring back the Windows 10 taskbar and add some other improvements. (As a free alternative, there's also [explorerpatcher](https://github.com/valinet/ExplorerPatcher)) Using this allows me to use the deskband. I noticed, however, that the deskband icon doesn't fit well with the design of the rest of the OS. After going through the code, I saw you drew the icon using paths. Would replacing this with an icon from the font be possible? The icon for this is E721 in the icon fonts. It'd make it all more coherent, I think. It only affects the deskband, not the launcher, as it uses dedicated icon files.

### Alternatives Considered

I have tried implementing these things myself, but I don't know how to code. I can look between the lines and guess, but that's it, unfortunately. I could make a pull request for the Segoe fluent icons font change, but that's two lines of code and would probably break icons on Windows 10 - I don't think that would be worth it. Sorry for not being of much use here.

**Comment by stnkl** [comment]
Thank you for the excellent feature request! I will take a look at what I can do when I get the time. I have also thought about FluentWPF before but didn't look at the details yet.

**Comment by nguyenkien** [comment]
> Hey there, after some more digging, I found another great library that might be better than the two libraries I mentioned before. It's called [WPFUI](https://github.com/lepoco/wpfui). It seems to be much more mature than the ones linked before, having over double the stars on its repository and excellent documentation [here](https://wpfui.lepo.co/documentation/).

I would prefer [ModernWpf](https://github.com/Kinnara/ModernWpf)

**Comment by stnkl** [comment]
Thanks again @kronuschan for the excellent feature request. I took all of your suggestions into account. EverythingToolbar is now using the Windows 11 Acrylic windows and an up to date design.
