### ISSUE TITLE
Bug: Only first letter inputted via experimental menu search replacement after windows key press

### ISSUE THREAD

**Issue by piebaker** [stnkl/EverythingToolbar#250]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.8.0.0

### Windows Version

Windows 10 Education 21H2

### Steps to reproduce

Enable Replace Start Menu Search
Press windows key
Begin typing search

### Expected Behavior

Keyboard input is read as normal

### Actual Behavior

Only the first letter is read, all other keyboard input is ignored

### Log output

No log file was generated
(Wut)

### Additional Information

Seems to be inconsistent, both when pressing the windows search button and when using the windows key then typing

**Comment by stnkl** [comment]
Hi @piebaker, are you using the deskband or the launcher icon? In case you are using the launcher icon (a regular application icon pinned to the taskbar) I would suggest you use the deskband instead by right-clicking the taskbar and enabling the toolbar "Everything Toolbar" as shown in the setup video in the readme.

**Comment by piebaker** [comment]
I am using neither. Instead I enabled the experimental replace start menu search option, and simply press the windows key and start typing. This saves having to use the mouse, as I can simply press the windows key and type to begin the search

**Comment by stnkl** [comment]
But which version did you use to enable the experimental start menu replacement option? You must have either enabled the taskbar deskband extension or there must be a process running in the background which you can see in the system tray.
