### ISSUE TITLE
Relocating the search icon on the taskbar?

### ISSUE THREAD

**Issue by MostHated** [stnkl/EverythingToolbar#26]
Hey there, 
    I was wondering if there is an easy way to move the position of the search icon on the taskbar? It is over to the right side, which I already have a fair amount of things setup. I tried to see if there was an option to have it appear elsewhere just from the settings but didn't see one, I also tried just unlocking the taskbar and seeing if I could drag it, but no luck there. Is this something that can be done in a customized theme or similar?

You can see it here in the middle, it took me a bit to notice it even appeared on the taskbar when I enabled it, and I really don't want to have to go and change my RainMeter theme, I just would prefer to have the search on the left side of the taskbar.
![](https://i.imgur.com/VG7A9GW.png)

Thanks,
-MH

**Comment by Darthagnon** [comment]
It is draggable for me, but it is quite difficult/finicky to drag. Don't know if there's a solution, as Windows automatically puts all new toolbars on the right-hand side.

**Comment by MostHated** [comment]
It must be. It seems like it should be draggable, especially the actual toolbar container, but I can't seem to get it to do so.. strange.

**Comment by Horst12** [comment]
I have it on the left side and dragged the other icons to its right,
That was esier than dragging the Toolbar icon itself.

**Comment by stnkl** [comment]
Moving deskbands on the taskbar is a little fiddly. I attached a short gif which hopefully explains how to move around deskbands.

Notice a few things:
1. The taskbar has to be unlocked (right click the taskbar and uncheck "lock the taskbar")
2. You can't drag deskbands when the mouse is too close to the screen edge (as you can see in the gif).
3. When dragging it out of the taskbar (in my case the top of the taskbar) it just disappears (very end of the gif). In that case disable and reenable the toolbar to make it show up again.

![dcdOJutZAa](https://user-images.githubusercontent.com/17520641/99551638-64671600-29bc-11eb-94de-509a0d6e3604.gif)

Unfortunately it's implemented that way in Windows so there is no way for me to change that.

**Comment by MostHated** [comment]
Ok, I got this figured out. It was my bad for not realizing it at first, but I had to stop FalconX/TaskbarX first, which then let me move it, then restarted TaskbarX, now it shows up on the left side.

![](https://i.imgur.com/YzOHP9T.png)

**Comment by stnkl** [comment]
Glad it worked out for you!
