### ISSUE TITLE
Add setup assistant strings to Crowdin

### ISSUE THREAD

**Issue by dracp** [stnkl/EverythingToolbar#266]
### Discussed in https://github.com/stnkl/EverythingToolbar/discussions/262

<div type='discussions-op-text'>

<sup>Originally posted by **dracp** September 25, 2022</sup>
Unable to translate the contents of the new ET 0.8.0 beta 1 startup interface.
In Crowdin, the new strings corresponding to this interface are not found.

![220925 ET 0 8 0_b1_Interfaz inicio_Crowdin_No traducido](https://user-images.githubusercontent.com/102802425/192135878-1f53b017-7f7f-44e1-a48c-8ee708e5a209.png)
</div>

**Comment by stnkl** [comment]
I added all strings related to the Windows 11 setup assistant. They can now be translated with [Crowdin](https://crowdin.com/project/everythingtoolbar)!

**Comment by dracp** [comment]
**ET 0.80.b2. Setup Assistant NOT TRANSLATED**

1. The title of the Setup Assistant is not translated. If it is translated in Crowdin. 

![221004 ET 0 8 0_b2_Encabezamiento_Interfaz inicio_Sin traducir](https://user-images.githubusercontent.com/102802425/193805768-1eb998c9-5bb1-44c0-a924-ea034b46c8d9.png)

2. The "Restart explorer" pop-up box after closing the Wizard is not translated. chains are not found in Crowdin.

![221004 ET 0 8 0_b2_Cuadro emergente_Restaurar explorador_Sin traducir](https://user-images.githubusercontent.com/102802425/193805897-b01b6952-ba3a-4a16-8269-be49312eb69c.png)

**Comment by stnkl** [comment]
Sorry, I forgot about those. They are now fixed.

**Comment by dracp** [comment]
> Sorry, I forgot about those. They are now fixed.

Ok
I finish translating it in Crowdin.

**Comment by stnkl** [comment]
> NOTE Sorry, one question, are the modifications now included in ET 0.80-beta2 or to check it I have to wait for a new beta?

The changes will be available in the next release. I'm not sure when it will be released though.
