### ISSUE TITLE
"Deskband host for wpf" shows instead of toolbar

### ISSUE THREAD

**Issue by CruxH** [stnkl/EverythingToolbar#27]
Looks like same behavior as described in [issue #3](https://github.com/stnkl/EverythingToolbar/issues/3).

Uninstalling working v0.4.0, restarting explorer, installing v0.5.0 and restarting explorer again registers the toolbar correctly - toolbar is available for selection - but once selected, appears as "Deskband host for wpf" window on the taskbar.

Reverting back to v0.4.0 results in a working toolbar.

**Comment by stnkl** [comment]
I suspect there is a problem with registering the `Win+Alt+S` hotkey. Could you please try this version and see if the issue is resolved? If that is the case I would be interested in the log file output. You can find it at `%TEMP%/EverythingToolbar.log`.

[EverythingToolbar-0.5.1.zip](https://github.com/stnkl/EverythingToolbar/files/5567997/EverythingToolbar-0.5.1.zip)

**Comment by CruxH** [comment]
Same behavior with v0.5.1. 

There's but a single line in the log file after restarting explorer:

`2020-11-19` 22:48:16.7876|INFO|EverythingToolbar started. Version: 0.5.1.0, OS: Microsoft Windows NT 10.0.19042.0|

**Comment by stnkl** [comment]
Version 0.5.2 has improved logging. Could you try this one and post the log file output again please? Expect some styling issues this time.

**Comment by CruxH** [comment]
Remains a no-go.

Nothing additional in the log file except for the below line, that duplicates itself with an updated timestamp every time 'Everything Toolbar' is selected at the Window toolbar > Toolbars section:

`2020-11-21 10:46:02.4797|INFO|EverythingToolbar started. Version: 0.5.2.0, OS: Microsoft Windows NT 10.0.19042.0|`

**Comment by stnkl** [comment]
I accidentally just reproduced this issue while developing and fixed it by removing the settings file. For me it is located at `%LocalAppData%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\10.0.19041.610\user.config`. If you can't find it there just search for `user.config` using Everything. It should contain the string `EverythingToolbar.Properties.Settings`. You can safely delete it and see if it works after that.

**Comment by CruxH** [comment]
At `%LocalAppData%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\` there are two folders: `10.0.19041.1` and `10.0.19041.610`, with `user.config` file in each. Their `EverythingToolbar.Properties.Settings` block appears to be different -

`10.0.19041.1` is below:

```
        <EverythingToolbar.Properties.Settings>
            <setting name="isDetailedView" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isRegExEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="sortBy" serializeAs="String">
                <value>1</value>
            </setting>
        </EverythingToolbar.Properties.Settings>
```

`10.0.19041.610` is below:

```
        <EverythingToolbar.Properties.Settings>
            <setting name="theme" serializeAs="String">
                <value>Dark</value>
            </setting>
            <setting name="popupSize" serializeAs="String">
                <value>700,700</value>
            </setting>
            <setting name="isDetailedView" serializeAs="String">
                <value>True</value>
            </setting>
        </EverythingToolbar.Properties.Settings>
```

Deleting this block in the .610 `user.config` didn't solve the issue.

**Comment by stnkl** [comment]
I actually meant deleting the files in both folders completely. I can reproduce the issue by changing the `PublicKeyToken` in the `section` tag to something random. By deleting the files it will get reset.

Sorry for you being the guinea pig here. I'm poking in the dark here as I didn't do enough reading on this yet.

**Comment by CruxH** [comment]
No problem, I'd like to help you solve this.

Tried the following:

1. Uninstalled EverythingToolbar v0.4.0
2. Killed `explorer.exe`
3. Deleted `user.config` in both folders
4. Launched `explorer.exe`
5. Installed EverythingToolbar v0.5.2
6. Restarted `explorer.exe`
7. Enabled the toolbar in taskbar settings

This again resulted in "Deskband host for wpf" window and no new `user.config` was created anywhere in the system.

Uninstalled v0.5.2, reinstalled v0.4.0 and it launched successfully. No `user.config` file was created. After toggling any setting (e.g., changing theme), a new `user.config` was created in the `10.0.19041.610` folder.

**Comment by stnkl** [comment]
Hi, sorry for keeping you waiting. Would it be possible to try 0.6.0-beta2 again? I didn't do anything specific to fix this issue (as I still don't know what's causing it) but at least now I am fairly certain that the log files should give us *something*.

You can download it directly: [EverythingToolbar-0.6.0-beta2.zip](https://github.com/stnkl/EverythingToolbar/files/5724881/EverythingToolbar-0.6.0-beta2.zip)

**Comment by CruxH** [comment]
Version 0.6.0-beta2 actually worked.

Couple of issues though:

1. Text looked considerably more blurry than v0.4.0. I'm at 125% DPI.
2. When entering characters into the search field, deleting some of them and repeating 2-3 times, explorer.exe would hang, at which time the log showed an exception:

```
2020-12-22 15:30:51.6169|INFO|EverythingToolbar started. Version: 0.6.0.0, OS: Microsoft Windows NT 10.0.19042.0|
2020-12-22 15:30:51.8274|INFO|Everything version: 1.4.1|
2020-12-22 15:31:26.6725|ERROR|Unhandled first chance exception|System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2020-12-22 15:35:55.5170|INFO|EverythingToolbar started. Version: 0.6.0.0, OS: Microsoft Windows NT 10.0.19042.0|
2020-12-22 15:35:55.7100|INFO|Everything version: 1.4.1|
2020-12-22 15:36:00.0220|ERROR|Unhandled first chance exception|System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
```

**Comment by stnkl** [comment]
That's good to hear!

1. That is the case for me too at non-standard scaling factors. I will have a look at that.
2. Do you have any slower drives (external drives or non-SSD) connected to your computer? I noticed the same when I had an external hard drive connected that still had to spin up.

**Comment by CruxH** [comment]
1. Great!
2. System drive is SSD, and an additional mix of SSD and mechanical drives other than that, no external drives. Doesn't reproduce with v0.4.0 in same conditions.

**Comment by Darthagnon** [comment]
Maybe a "loading" animated icon could help people wait through the freezes from external HDDs loading?

**Comment by stnkl** [comment]
> Maybe a "loading" animated icon could help people wait through the freezes from external HDDs loading?

If I understood @CruxH correctly the whole explorer freezes making taskbar/start menu unresponsive. 

Normally getting search results should be almost as instant as in Everything (with a little overhead).

**Comment by CruxH** [comment]
> If I understood @CruxH correctly the whole explorer freezes making taskbar/start menu unresponsive.

That's correct - taskbar and start menu become unresponsive. The issue is easily reproducible on my end with v0.6.0-beta3, while repeating same steps doesn't cause it with v0.4.0.
