### ISSUE TITLE
Feature: Please use WinGet Releaser

### ISSUE THREAD

**Issue by ppvnf** [stnkl/EverythingToolbar#273]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I believe EverythingToolbar is already on Winget and it seems up to date (regular version), but would it be possible to use https://github.com/marketplace/actions/winget-releaser to make beta versions also up to date automatically? There's a package called stnkl.EverythingToolbar.Beta https://github.com/microsoft/winget-pkgs/pull/80762/commits/ab711199c26d024feff079472b923146723f15ec, but it's already outdated. Thanks.

### Proposed Solution

Configure https://github.com/marketplace/actions/winget-releaser to make releases of EverythingToolbar Beta automatically available on Winget

### Alternatives Considered

I am not very knowledgeable about Winget, but maybe also automate the regular version (if it is not already automated by someone else).

### Additional Information

It seems WinGet Releaser needs a token authentication. I don't know how to upload manifests to Winget, but maybe it's possible to get help at https://github.com/microsoft/winget-pkgs

**Comment by vedantmgoyal2009** [comment]
The following are the requirements that need to be completed before implementing the action. Also, I can create the PR to add thw workflow if the maintainer would like.
1. Please add a GitHub token with `public_repo` and `workflow` scopes as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @stnkl.

**Comment by stnkl** [comment]
Thank you for the suggestions and sorry for the late reply. I decided to use winget-create for automatic releases. 😊
