### ISSUE TITLE
Bug:  typing content when using Microsoft Pinyin

### ISSUE THREAD

**Issue by SrSh-notme** [stnkl/EverythingToolbar#274]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.8-beta2

### Windows Version

win 11 22h2

### Steps to reproduce

1. open toolbar
2. input chinese by using Microsoft Pinyin
3. the characters shoud be shown in the input box of the toolbar

### Expected Behavior

the characters shoud be shown in the input box of the toolbar

### Actual Behavior

the characters were in the upper left corner

### Screenshots

![image](https://user-images.githubusercontent.com/48594308/194715017-3f0112cb-a485-46d4-9756-3e67093712a0.png)

### Log output

cannot find the log

**Comment by stnkl** [comment]
Thank you for the bug report. This has been fixed in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0).
