### ISSUE TITLE
Bug: Taskbar and tray icon is not readable in dark mode

### ISSUE THREAD

**Issue by chungchungdev** [stnkl/EverythingToolbar#279]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.8.0.1

### Windows Version

Windows 11 22H2 22621.674

### Steps to reproduce

1. Settings -> Personalization -> Set dark mode

### Expected Behavior

A readable icon. e.g. the same magnifier icon with white border

### Actual Behavior

![everything dark icon](https://user-images.githubusercontent.com/78669528/199186076-b8bd6bfb-be36-4b75-ab83-1b1033519c31.png)

### Log output

not applicable

**Comment by stnkl** [comment]
Hi, as far as i know it's not possible to change the icon reliably without restarting Windows explorer. So this might just be a limitation of the Windows 11 launcher.

**Comment by chungchungdev** [comment]
If coding cannot solve the problem at the moment, changing the design could do the trick.
e.g. 
- select a color that is readable in both light and dark theme (like the Everything icon)
- add complementary color border or background to the icon (like Logitech g hub icon)

**Comment by stnkl** [comment]
Thanks for the suggestions. I took them into account in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0). You can now select out of three icon choices (dark, light and a blue search icon).
