### ISSUE TITLE
Bug: context does not focus on highlighted search result

### ISSUE THREAD

**Issue by KeronCyst** [stnkl/EverythingToolbar#284]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.7.4

### Windows Version

Windows 10 Home 22H2

### Steps to reproduce

1. Launch ET and enter a search query
2. Receive results
3. Press the Down arrow one time or more to highlight any result
4. Press the Apps Key (Shift-F10)

### Expected Behavior

The context menu should target the highlighted file

### Actual Behavior

The context menu applies to the search query field instead, but this should only happen if you never pressed the Down arrow

### Log output

2022-12-02 10:09:35.9880|INFO|EverythingToolbar started. Version: 0.7.4.0, OS: Microsoft Windows NT 10.0.19045.0|
2022-12-02 10:09:36.5115|ERROR|IPC is not available.|
2022-12-02 10:09:36.5115|ERROR|Failed to get Everything version number. Is Everything running?|

**Comment by stnkl** [comment]
Thanks for opening the bug report. This behaviour is already tracked in #101.
