### ISSUE TITLE
Please allow choosing between Windows 10 or 11 style for scrollbar

### ISSUE THREAD

**Issue by lucaspestana** [stnkl/EverythingToolbar#290]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I appreciate that the developer updated EverythingToolbar to use Windows 11's new Fluent scrollbars.
The only problem is… I personally don't like them; I prefer the Windows 10 style, blocky, bulkier scrollbar.

### Proposed Solution

Please add an option in settings to choose one of the two (or more) scrollbars.
I would also like to suggest, if that's not too difficult to implement, another scrollbar, that only becomes visible during scrolling or when the cursor is on near the edge of the search box, and disappears from view otherwise.

### Alternatives Considered

I suppose downgrading? That's the only thing I can think of, and one I would really rather not do.

**Comment by stnkl** [comment]
Thanks for opening the issue! Currently, the way that Windows 10 and 11 skins are implemented doesn't easily support switching out different parts of the skin, so this cannot easily be done. Long-term I want to have a better solution for handling multiple skins, given the fact that style changes will probably come more regularly with new Windows versions. For now, I tracked all feature requests related to this in #147. Once I have the time to revamp the system, I will take all linked issues into consideration. Therefore I will close this issue now.

**Comment by stnkl** [comment]
The latest release allows you to switch out individual styles from Windows 10 and Windows 11. This way you can revert back to the old scrollbar design. To do that, install the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0) and switch out the `Scrollbar.xaml` files in the installation directories of EverythingToolbar.

**Comment by lucaspestana** [comment]
I'll look into it over the next few days. Thank you so much for this!
