### ISSUE TITLE
No taskbar context menu to enable from in win11

### ISSUE THREAD

**Issue by xoorath** [stnkl/EverythingToolbar#291]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.7.4

### Windows Version

Windows 11

### Steps to reproduce

1. Install Everything Toolbar
2. Right click taskbar context menu
3. Right click taskbar context menu again

### Expected Behavior

The [readme](./readme.md) indicates an option to enable the toolbar should be present.

### Actual Behavior

The only option is "Taskbar Settings".

### Screenshots

![image](https://user-images.githubusercontent.com/769014/207435491-3a8afcb6-a36a-4787-b7fd-e6cb5a2aea6a.png)

### Log output

no log output / everything toolbar is not running.

### Additional Information

I'm assuming there's some other way to enable the toolbar that just needs to be reflected in the readme.

Thanks for any help.

**Comment by stnkl** [comment]
For Windows 11 support you have to upgrade to the latest beta release of EverythingToolbar 0.8.1. Here are instructions on how to set it up on Windows 11: https://github.com/stnkl/EverythingToolbar/discussions/245#discussioncomment-3182799

**Comment by xoorath** [comment]
> For Windows 11 support you have to upgrade to the latest beta release of EverythingToolbar 0.8.0. Here are instructions on how to set it up on Windows 11: [#245 (comment)](https://github.com/stnkl/EverythingToolbar/discussions/245#discussioncomment-3182799)

I would suggest keeping this ticket (or some ticket) open to track that this isn't in the readme at least. Just my $0.02.

Good luck getting similar functionality into Windows 11. This project is cool.

**Comment by stnkl** [comment]
Thanks, I added a small note in the readme for now. I will get back to working on the stable release of 0.8.0 soon and will update the readme properly then.
