### ISSUE TITLE
[bug] Toolbar not showing

### ISSUE THREAD

**Issue by TheRealBix** [stnkl/EverythingToolbar#3]
`RegAsm : warning RA0000 : Lorsqu'un assembly non signé est inscrit avec /codebase, il peut interférer avec d'autres applications installées sur le même ordinateur. Le commutateur /codebase doit uniquement être utilisé avec des assemblys signés. Affectez à votre assembly un nom fort et l'inscrire à nouveau.
Succesfully registered deskband `Everything Toolbar` - GUID: {aa01acb3-6ccc-497c-9ce6-9211f2edfc10}
Inscription des types réussie
Appuyez sur une touche pour continuer...`

This is what is told when launching the install.cmd file. 
Installation seems to be fine tho as "Everything Toolbar" is available in right click menu.

Enabling the toolbar does nothing except opening "ghost windows" : 
![image](https://user-images.githubusercontent.com/4289656/94082447-425c7780-fe01-11ea-808c-e349bc905a18.png)

I have version 2004 of Windows, .NET framework version seems to be superior to 4.8

**Comment by IIEleven11** [comment]
I'm having the same issue. I tried downlaoding dev pack 4.7 and tried cloning the repo. Visual studio is telling me I am missing the Everything toolbar.pfx file though. I can see it in solution explorer I believe. I just cant get to it in file explorer.
![image](https://user-images.githubusercontent.com/55998857/94959806-a7ba0380-04a6-11eb-8613-680c33d5dc72.png)

**Comment by stnkl** [comment]
I am using the pfx-file to sign the assembly. You can disable signing in the project properties under the "Signing" tab. It should build then.

I have tried to get to the root of this issue already but I'm not getting anywhere. I appreciate your effort in helping out!

**Comment by TheRealBix** [comment]
Hi, I've just tried installing it on Sandbox, same result 
![image](https://user-images.githubusercontent.com/4289656/94973397-da4a1780-050b-11eb-8332-dd8dead18c31.png)

Sorry for not beeing that useful

**Comment by stnkl** [comment]
@IIEleven11 I added a debug project so we can actually debug the application. Could you do me a favor and pull the latest changes, set the EverythingToolbar.Debug project as startup project (right click the project) and run it with the debug configuration?

@TheRealBix Don't worry about it. Anything helps!

**Comment by IIEleven11** [comment]
Just saw this, yeah ill do that

**Comment by IIEleven11** [comment]
So i recieved an "Everythingtoolbar.dll not found." So I went and pasted it in the correct file and ran the debugger again. I also disabled signing and got this screnshot. Just fyi i'm on third level c++ in college. So I dont know how to use Git real well. And as far as debugging this, I am not too sure how to go about things beyond putting a missing file in the right place. But hey if I can do anything else to help let me know. I still have not been able to get it to function properly. It boots me out of explorer.exe everytime i run it in Visual studio as well. 
![image](https://user-images.githubusercontent.com/55998857/95195454-68800100-078b-11eb-81c4-8752537791c3.png)

**Comment by stnkl** [comment]
@IIEleven11 

When building the solution every project gets built. In this case the main project failed to build because the NLog package has not been installed. That's why no EverythingToolbar.dll was created. To fix that navigate to _Tools > NuGet package manager > Manage NuGet packages for solution..._ and click the _Restore_ button in the top right. If the restore button doesn't appear just search for "NLog" in the _Browse_ tab and install it for the _EverythingToolbar_ project. Also please check again if signing is disabled for that project.

The first error in your error list stems from the fact that you pasted an outdated EverythingToolbar.dll into the bin folder.

Restarting explorer.exe is intended so VS can overwrite the EverythingToolbar.dll which would otherwise be locked.

You don't actually have to debug anything. I am just curious if it throws any unhandled exceptions when running it on your machine.

**Comment by stnkl** [comment]
Could you try the latest release 0.2.3 and see if it fixes this issue?

**Comment by stnkl** [comment]
It appears that version 0.2.1 was broken. After removing version 0.2.1 make sure to restart windows explorer (or reboot your computer). Then install the latest version.

**Comment by mandyzhou** [comment]
Confirming that 0.2.3 fixes the issue for me.

**Comment by stnkl** [comment]
Awesome. Thank you!

**Comment by IIEleven11** [comment]
![image](https://user-images.githubusercontent.com/55998857/95582962-4d61fb00-09f0-11eb-99dd-083f3b39c6c8.png)
Looks good! I did get the .pfx error though. So I went and disabled signing and 100% error free. I used everything to look for the .pfx and couldnt find it on my PC.
