### ISSUE TITLE
Have I made a mistake?

### ISSUE THREAD

**Issue by TM1962** [stnkl/EverythingToolbar#30]
I have set the path in the "Rules" to Total Commander and saved it. Opening a search term via Total Commander will work (via: Context/OpenWith/TotalCommander Left) - but only until the next system start. Then you first have to enter and leave the "Rules" again (Save or Cancel doesn't matter), and then it works again. Until the next system start...

**Comment by stnkl** [comment]
Which version are you running? This should have been fixed in 0.5.2 (see #28).

**Comment by TM1962** [comment]
You are right. 0.5.2 works. Thanks.
