### ISSUE TITLE
Bug: "Replace Start Menu Search" does not work when toolbar is unchecked.

### ISSUE THREAD

**Issue by Andrew6rant** [stnkl/EverythingToolbar#305]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.7.4.0

### Windows Version

Windows 10 Education 21H2 19044.2486

### Steps to reproduce

1. Install EverythingToolbar
2. Right-click Windows 10's taskbar and check "Everything Toolbar" from Toolbars menu (to enable the program's toolbar)
3. Open up EverythingToolbar's Preferences and check "Replace Start Menu Search (experimental)" option
4. Right-click Windows 10's taskbar and uncheck "Everything Toolbar" from Toolbars menu (to hide the toolbar)

### Expected Behavior

EverythingToolbar's search window appears.

### Actual Behavior

Hitting the Windows key (or clicking on the icon) and typing does not do anything, neither Windows Start Search nor EverythingToolbar's search work.

### Log output

`Windows cannot find 'C:\users\agran\AppData\Local\Temp\EverythingToolbar.log' Make sure you typed the name correctly, and then try again.`

**Comment by stnkl** [comment]
Hi @Andrew6rant, thank you for the bug report. This was now fixed in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0). The start menu search will now work again after disabling EverythingToolbar.
