### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by bitsky6** [stnkl/EverythingToolbar#31]
Hello,

So I am trying to install but comes back with this error.

RegAsm : error RA0000 : Unable to locate input assembly '%~dp0EverythingToolbar.dll' or one of its dependencies.

I just run install.cmd as admin and it closes without showing me anything so I paste manually in cmd to see what is happening and this is what it writes.

Any ideea?

Thanks

**Comment by bitsky6** [comment]
> Hello,
> 
> So I am trying to install but comes back with this error.
> 
> RegAsm : error RA0000 : Unable to locate input assembly '%~dp0EverythingToolbar.dll' or one of its dependencies.
> 
> I just run install.cmd as admin and it closes without showing me anything so I paste manually in cmd to see what is happening and this is what it writes.
> 
> Any ideea?
> 
> Thanks

Ok so I fixed by replacing the "%~dp0EverythingToolbar.dll" with the direct location of the dll.
Thanks

**Comment by stnkl** [comment]
Normally it should not close after execution, even if there is an error. Could you do me a favor and run the install.cmd from within a cmd window and post the output here? You don't have to uninstall before that.

If you just paste the command from within the install.cmd it is expected to not work because `%~dp0` refers to the batch file location which there is none of when running directly from the command line.

**Comment by Horst12** [comment]
That should not happen if all files are in the same dir as the cmd file
which is the normal way to copy and install from the zip file.

**Comment by bitsky6** [comment]
I just extracted in a folder and ran the installer.
They where all in the same folder.

Anyway in case doesn't work I just change the location in the end.

Thank anyway.

----------------------------------------
László Pető
IT & AV Specialist
Live Sound Engineer
[cid:ii_a21814ce74be4519][cid:ii_4dd096457f714fcb]
[cid:ii_86dbb2397927472d][cid:ii_bbf9cd6281464d20]
[cid:ii_49246de2e7b64004]
Harman Certified Control Professional - Commissioning
Harman Certified Network AV Associate - Design
Harman Certified Network AV Professional - Commissioning
On Nov 22, 2020, at 12:19, Horst12 <notifications@github.com<mailto:notifications@github.com>> wrote:

That should not happen if all files are in the same dir as the cmd file
which is the normal way to copy and install from the zip file.

**Comment by bitsky6** [comment]
For some reason now is working also with the original command.
