### ISSUE TITLE
Search window always opens on main screen

### ISSUE THREAD

**Issue by nljxlove** [stnkl/EverythingToolbar#314]
### Preflight Checklist

- [ ] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

1.Multi-screen support needs to be optimized, and the software interface pops up on the main screen when clicking the search button in the taskbar of the secondary screen.
2.You want the taskbar tray area icon to be set to hidden.

### Proposed Solution

1.Multi-screen support needs to be optimized, and the software interface pops up on the main screen when clicking the search button in the taskbar of the secondary screen.
2.You want the taskbar tray area icon to be set to hidden.

### Alternatives Considered

1.Multi-screen support needs to be optimized, and the software interface pops up on the main screen when clicking the search button in the taskbar of the secondary screen.
2.You want the taskbar tray area icon to be set to hidden.

**Comment by stnkl** [comment]
> 1.Multi-screen support needs to be optimized, and the software interface pops up on the main screen when clicking the search button in the taskbar of the secondary screen.

Definitely something that can be fixed easily. Thank you.

> 2.You want the taskbar tray area icon to be set to hidden.

#255
