### ISSUE TITLE
Feature: Allow to Change Color Themes

### ISSUE THREAD

**Issue by KaiHuaDou** [stnkl/EverythingToolbar#319]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I use a "Windows Style Pack" which change my windows ui style. So I must keep my color mode to dark though the ui is light. But this app shows dark surface when use it.

### Proposed Solution

I hope there's an option that could change color theme instead of following the system.

### Alternatives Considered

Just add the options before the "Replace start menu search (experimental)".

**Comment by stnkl** [comment]
You can swap the `LIGHT.xaml` and `DARK.xaml` files in the installation directory of EverythingToolbar to invert the light and dark theme.

I don't plan to add an option to manually adjust the theme since the whole idea of EverythingToolbar is to seamlessly integrate into Windows.
