### ISSUE TITLE
Why it doesn't work?

### ISSUE THREAD

**Issue by ztmsimon** [stnkl/EverythingToolbar#32]
I install it well,but it doesn't work?
![image](https://user-images.githubusercontent.com/12029640/100178885-d46f2200-2f0f-11eb-9098-793ec51d9100.png)

**Comment by stnkl** [comment]
Could you please send the output of the EverythingToolbar.log? You can find it at `%TEMP%/EverythingToolbar.log`.

**Comment by ztmsimon** [comment]
[EverythingToolbar.log](https://github.com/stnkl/EverythingToolbar/files/5595962/EverythingToolbar.log)

**Comment by stnkl** [comment]
It looks like a running Everything instance could not be found. I have a few questions:

- Is Everything running in the background? 
- Did you install the full version of Everything? The Lite version is not supported.
- Are you running a 64bit or 32bit system? Currently only 64bit is supported.

**Comment by ztmsimon** [comment]
1.How do I know if Everything running in the background?

2.I download "EverythingToolbar-0.5.2.zip" and install.
![image](https://user-images.githubusercontent.com/12029640/100214820-4749be80-2f4b-11eb-96be-b3da228c44c8.png)

3.My computer OS is "64 位操作系统, 基于 x64 的处理器"."Windows 10 家庭中文版 20H2"
![image](https://user-images.githubusercontent.com/12029640/100214852-516bbd00-2f4b-11eb-9869-b60455e14afa.png)

**Comment by stnkl** [comment]
Everything Toolbar is only an small tool to get the search results of the search tool "Everything" into the taskbar. You have to download the full program Everything from https://voidtools.com (download 64-bit installer) first and have it running in the background (a tray icon should be shown in the bottom right corner of the taskbar.

**Comment by ztmsimon** [comment]
OK.Done!
Thank you!
![image](https://user-images.githubusercontent.com/12029640/100216162-ede28f00-2f4c-11eb-824c-d7dfb33d4465.png)
