### ISSUE TITLE
Feature: a shortcut button to launch native Everything UI

### ISSUE THREAD

**Issue by U11Leung** [stnkl/EverythingToolbar#321]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Now that the toolbar takes up some space in the taskbar, I plan to unpin Everything icon from taskbar to spare space for running app buttons, but by that I lose a convenient way to launch Everything itself, in the case that I want to look sth up in the full size Everything UI. Current UI of the apperaed pane of toolbar doesn't give me a way, a shortcut to launch Everything.

### Proposed Solution

Just add a button aside the three dot menu button to act as a launch button is ok, in that way I can activate toolbar pane and then click the shortcut button right away.

### Alternatives Considered

Nothing to provide.

**Comment by stnkl** [comment]
You can already do that in two ways:

- Open the highlighted search result in Everything either via its context menu or by pressing <kbd>Shift</kbd>+<kbd>Enter</kbd>/<kbd>Click</kbd>

- Enable the option to display the number of search results in the top right corner of the search window. Clicking on the number of search results will open the current search in Everything. So if you don't have the "Hide empty search" option enabled you should always be able to launch Everything that way. ![image](https://user-images.githubusercontent.com/17520641/216107353-e5735269-a39c-4568-bf4e-1836f8d5a6f3.png)

**Comment by U11Leung** [comment]
Didn't know the second one, I will take that as the answer for me, thank you
