### ISSUE TITLE
Everything search icon appears in systray, no input field

### ISSUE THREAD

**Issue by WisseJ** [stnkl/EverythingToolbar#34]
Hi, I just installed Everything Toolbar. Ran Install.cmd as administrator, selected Everything Toolbar in Taskbar properties. Had to restart Explorer.exe. Everything Toolbar Icon appears in systray but no input field. When I type, the result window appears, so it´s running. I´m on Windows 10 x64 version 20H2. Tried to uninstall and reinstall but same result. Any ideas?

**Comment by stnkl** [comment]
By default it starts as a small icon. You have to unlock the taskbar via the context menu and pull the handle to make it wider. There is a little further information [here](https://github.com/stnkl/EverythingToolbar/issues/26#issuecomment-729766987).

**Comment by WisseJ** [comment]
Great, that did the trick. Thanks a lot!

**Comment by NicoJuicy** [comment]
PS. Don't forget if the taskbar is locked, you can't pull the handle to make it wider :)
