### ISSUE TITLE
the shorcut_key will be failed.

### ISSUE THREAD

**Issue by iesvme** [stnkl/EverythingToolbar#35]
my system: win10 1809_64
when I type "win+alt+s, tab, tab", and then the the shorcut_key will be failed. it can't work anymore.

**Comment by Horst12** [comment]
sorry, but why do you type tab tab after win+alt+s ?
This focuses the toolbar search field and you can start to type your search text.
What should be the logic for searching  tab tab ?

**Comment by iesvme** [comment]
No, it is just a typo. However, is it a bug?

**Comment by stnkl** [comment]
This will be fixed in the next release. You will be able to use Tab and Shift+Tab to cycle through filters.
