### ISSUE TITLE
It cannot open the first item when typing the Enter key.

### ISSUE THREAD

**Issue by iesvme** [stnkl/EverythingToolbar#36]
It cannot open the first item when typing the Enter key.

**Comment by Horst12** [comment]
Works here with any result in the first line

**Comment by iesvme** [comment]
sorry, but what do you mean?

**Comment by stnkl** [comment]
@iesvme Currently you have to select the first search result with the down arrow before opening it with Enter. I think you are asking for preselection of the first search result to make it easier to open?

**Comment by iesvme** [comment]
Yes. It can be as the same as everything selecting the first line without down arrow. thank you for your reply.

**Comment by Horst12** [comment]
> 
> 
> Yes. It can be as the same as everything selecting the first line without down arrow. thank you for your reply.

That has a big disadvantage in case you want to modify the search.
Then the list has the focus and you cant just change your search term

**Comment by stnkl** [comment]
> That has a big disadvantage in case you want to modify the search.
> Then the list has the focus and you cant just change your search term

Don't worry about it. The search box will always stay keyboard focused.
