### ISSUE TITLE
repeat result

### ISSUE THREAD

**Issue by iesvme** [stnkl/EverythingToolbar#37]
when typing Chinese it will show repeat result.

**Comment by stnkl** [comment]
Why did you close the issue? I didn't get around to trying to reproduce it yet.

**Comment by iesvme** [comment]
Because the one who has the same issue as me.

**Comment by stnkl** [comment]
So the issue is not specific to Chinese characters?

**Comment by stnkl** [comment]
Did 0.6.0-beta1 fix the problem for you?

**Comment by iesvme** [comment]
Of course, thank you so much！

**Comment by stnkl** [comment]
Awesome. Thank you!
