### ISSUE TITLE
[Feature Request]: custom tab like: word, excel, pdf, zip files

### ISSUE THREAD

**Issue by yunlongYoung** [stnkl/EverythingToolbar#38]
For daily office use, a tab like word, excel, pdf, zip files etc. is convenient.  This allow us to filter file in simple.

And another question, how to print docx and xlsx files with "open with", what should I set to the Rules.

I tried this

Name | Type | Regular Expression | Command
Print | File | .*(docx\|doc\|xls\|xlsx) | Get-Content -Path %file% | Out-Printer

`
 Get-Content -Path %file% | Out-Printer
`
command is using Powershell,
but has no effect.

**Comment by Horst12** [comment]
Why should this construct work ?
There is no command like Get-Content in Windows, its only known by Powershell.
You would have to provide an Powershell script and use the for example Pwsh.exe to execute it.

**Comment by stnkl** [comment]
1. This has already been requested in #5 and will be available in the future.

2. Like @Horst12 said you can't run Powershell commands from cmd.exe directly. Instead run it like this:
`powershell -windowstyle hidden -command Get-Content -Path %file% | Out-Printer`
