### ISSUE TITLE
Display Problem

### ISSUE THREAD

**Issue by shtu-cham** [stnkl/EverythingToolbar#39]
Hi Developer,

Now I install Everything Toolbar, but when I pin it on my taskbar, I can't see the whole toolbar and don't know what went wrong, so I ask for your help. Thank you!

![image](https://user-images.githubusercontent.com/49547877/101270881-8207ee00-37b8-11eb-9575-4fc0f4bc3744.png)

**Comment by stnkl** [comment]
You have to unlock the taskbar via the context menu and drag the handle to increase the size. See #34.

**Comment by shtu-cham** [comment]
> You have to unlock the taskbar via the context menu and drag the handle to increase the size. See #34.

Thank you! Appreciate your work!
