### ISSUE TITLE
Everything toolbar not integrating with taskbar search feature

### ISSUE THREAD

**Issue by demdante** [stnkl/EverythingToolbar#40]
I am not sure if I am doing something wrong or if this is a bug, but I have tried installing the Everything toolbar, but the Everything toolbar is not integrating with the Windows toolbar's built-in search box as is demonstrated on this repo's main page.  Instead, when enabled, the Everything Toolbar is creating a separate icon on the other side of the toolbar, and, when clicked, does not display anything until the user starts typing.  See below.

![every](https://user-images.githubusercontent.com/64720591/101273752-1578f900-3790-11eb-8923-4807eb44c015.gif)

**Comment by shuiRong** [comment]
same situation.

**Comment by stnkl** [comment]
EverythingToolbar does not integrate into the Windows search. Instead it is a separate search bar that mimics Windows 10's search function. 

You have to disable the Windows search bar (context menu of task bar), then unlock the taskbar and drag EverythingToolbar to the left side. See #34 for more information.
