### ISSUE TITLE
The search results show duplicates,but there is only one actual file. 

### ISSUE THREAD

**Issue by fjj739964256** [stnkl/EverythingToolbar#43]
![image](https://user-images.githubusercontent.com/33320479/102188532-5db2bc80-3ef0-11eb-8243-69b83f76f3eb.png)
Restarting the computer and rebuilding the index cannot be resolved.How to solve this problem？

**Comment by stnkl** [comment]
This appears to be a common issue for some users (#20, #33, #37). I am working on a fix.

**Comment by stnkl** [comment]
This should be fixed in 0.6.0-beta1. Could you please check that for me?

**Comment by fjj739964256** [comment]
> This should be fixed in 0.6.0-beta1. Could you please check that for me?

Sure.No problem.
