### ISSUE TITLE
[Enhancement] Publish to Chocolatey

### ISSUE THREAD

**Issue by Clazex** [stnkl/EverythingToolbar#45]
Publish this to [Chocolatey](https://www.chocolatey.org/)

**Comment by Soitora** [comment]
Also to [Winget](https://github.com/microsoft/winget-pkgs) as that's the upcoming official Windows package manager

**Comment by Horst12** [comment]
> 
> 
> Also to [Winget](https://github.com/microsoft/winget-pkgs) as that's the upcoming official Windows package manager

There is no upcoming Windows package manager.
Thats all rumors which exists since years and non of the proposed tools have any big market share.

**Comment by Soitora** [comment]
> > Also to [Winget](https://github.com/microsoft/winget-pkgs) as that's the upcoming official Windows package manager
> 
> There is no upcoming Windows package manager.
> Thats all rumors which exists since years and non of the proposed tools have any big market share.

Please refrain from making comments like this on subjects that are super easy to fact check.

If there is no "upcoming Windows package manager" then I guess someone hacked the Microsoft GitHub account and published a working tool with a clear timeline of future updates for it: https://github.com/microsoft/winget-cli

**Comment by stnkl** [comment]
Today I had a look at how to publish to Chocolatey and WinGet and noticed `everythingtoolbar` is already available via WinGet thanks to @OfficialEsco. Thanks for that!

Also @niks255 [submitted](https://community.chocolatey.org/packages/everythingtoolbar) it to Chocolatey where is it currently under review. Thank you as well!

I will update the readme once the Chocolatey submission is complete.

**Comment by niks255** [comment]
There's a minor issue I need to fix with it, then it will probably be approved.
If you'd like to take over - be my guest.

**Comment by niks255** [comment]
> I will update the readme once the Chocolatey submission is complete.

Well, the time has come :)

**Comment by stnkl** [comment]
> Well, the time has come :)

Awesome! Sorry for not replying earlier. Do you think it would be more fitting to define `dotnetfx` &ge; 4.7 (as stated in EverythingToolbar's requirements) as the package dependency?

If you're okay with it you can stay the maintainer for now as I'm trying to focus on resolving other issues/requests with EverythingToolbar at the moment. I looked into the Chocolatey documentation regarding takeover of package maintenance but I find the documentation to be very confusing honestly.

I will update the readme probably later today. Thanks again!

**Comment by niks255** [comment]
> Awesome! Sorry for not replying earlier. Do you think it would be more fitting to define `dotnetfx` &ge; 4.7 (as stated in EverythingToolbar's requirements) as the package dependency?

Yeah, sure. Of course, if dotnetfx isn't installed, it will install the latest version anyway, so it won't change much.

> If you're okay with it you can stay the maintainer for now as I'm trying to focus on resolving other issues/requests with EverythingToolbar at the moment. I looked into the Chocolatey documentation regarding takeover of package maintenance but I find the documentation to be very confusing honestly.

I'll stay as a maintainer then, but you can always submit pull requests or contact me if there's an issue I need to fix.
