### ISSUE TITLE
Expose more resources for customization

### ISSUE THREAD

**Issue by iesvme** [stnkl/EverythingToolbar#47]
Could it customize the title of search box "Search with Everything"? 
How I wish it can!

**Comment by stnkl** [comment]
At the moment that is not possible. You can however change it's color by changing the theme files. If you just want to hide it completely you can set the color to `#00000000`.
I can add more style customizability in the future!

**Comment by iesvme** [comment]
by the way, it cannot hide the title "Search with Everything" when focusing search box.

**Comment by stnkl** [comment]
I just realized you can't actually change the watermark color individually. I'll add that functionality for stable 0.6.0 release.

**Comment by iesvme** [comment]
Thank you Stnkl! You're really a nice man!

**Comment by stnkl** [comment]
With the addition of a few translations (and more to come) I don't think there is any need to change the watermark anymore. Especially since it is already possible to hide it completely using the theming approach. This is why I am closing this issue.
