### ISSUE TITLE
Setting the Position

### ISSUE THREAD

**Issue by Astra060** [stnkl/EverythingToolbar#470]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Hey. When I change the position of pop up by dragging the left side of the window, it automatically switches back to default. This only happen with dragging the left side of the pop up

### Proposed Solution

save the position in a config for each resolution and then use a default preset for when resolution changes like running older or heavier games which need lower resolutions

### Alternatives Considered

needs non

**Comment by srwi** [comment]
Hi @Astra060, this is by design. The window should automatically be placed just like the windows Start menu. Adding custom placement is not planned.
