### ISSUE TITLE
Hide results when the search is empty

### ISSUE THREAD

**Issue by anonimuos** [stnkl/EverythingToolbar#49]
Just tried Everything Toolbar 0.6.0.0 and it is great. It is evolving very nicely. I would like to say thanks for the 3 features I requested which are implemented and work beautifully:

- Custom hotkey to invoke it works brilliantly
- Compact View with Details is superb
- Pressing Win key closes it too (since Win key is very close to my hotkey: Ctrl+Shift+E).

I have 1 more feature request and 1 minor change request:
- Everything comes with an option "Hide results when the search is empty" that opens a clean window and only shows results when a search is done. Would it be possible to have this for the toolbar?

The change request is actually very minor: make the same hotkey close the toolbar again which opens it (kind of like how Win key opens and closes the Start menu).

Thank you very much for an awesome tool. This speeds up workflow when finding anything quickly.

**Comment by stnkl** [comment]
Thank you, I really appreciate the kind words!

It shouldn't be a problem adding an option for that. The hotkey toggle change is a good suggestion too!

**Comment by stnkl** [comment]
Both is available in 0.6.0 stable now!
