### ISSUE TITLE
[Enhancement] Add all filters available in Everything

### ISSUE THREAD

**Issue by swarup459** [stnkl/EverythingToolbar#5]
It would be nice if all the filters like Audio, Document, Executable etc are available in search result. Right now only Files and Folders are shown.

Thank You.

**Comment by gepruts** [comment]
Filters are not available outside the Everything application.
So: not possible, unless EverythingToolbar defines it's own filters (and keep the file extensions in sync with Evrything somehow).

**Comment by stnkl** [comment]
[Void's answer](https://www.voidtools.com/forum/viewtopic.php?p=28357#p28357) to a related question. If I knew all the file extensions of each filter category I could implement it that way. Is that documented anywhere?

**Comment by gepruts** [comment]
You can either go to Menu:Search => Organize Filters and "edit" a filter
-or-
take a look at Fllters.csv (in the same folder as Everything.ini )

**Comment by perplexityjeff** [comment]
This would be a very welcome change as searching by a specific type of document or more easily searching for an application would be very helpful.

**Comment by stnkl** [comment]
Importing custom filters from Everything will be available in the next release.
