### ISSUE TITLE
Issue with display scaling

### ISSUE THREAD

**Issue by benvddriessche** [stnkl/EverythingToolbar#50]
When I do a new install of EverythingToolbar, the scaling of the app works fine. However, after a reboot, the scaling is off (see screenshot, other windows and taskbar for scale).

Set up:
- External monitor at 100% display scaling (3440x1440 resolution)
- DISABLED! Laptop monitor at 175% display scaling (3840 x 2160)
- Windows 10 20H2 (build 19042)
- EverythingToolbar 0.6.0 beta1 (but it occurred in previous releases as well)

![image](https://user-images.githubusercontent.com/20052906/102924986-94dd1c80-4460-11eb-8e96-337e8c4d35dc.png)

Edit: forgot to mention EverythingToolbar version

**Comment by stnkl** [comment]
Thanks for the report. I'll have to do some more work on correct display scaling. For now you would probably have to restart explorer via the task manager to fix the problem temporarily.

**Comment by benvddriessche** [comment]
Restarting explorer is indeed an easy quick fix for now, thanks.
And thanks for your work on this by the way. Fantastic tool already!

**Comment by stnkl** [comment]
Thanks for the kind words!

Version 0.6.1-beta1 has better scaling support. Hopefully it fixes the search box and popup scaling. However context menus and other windows will probably still be scaled incorrectly. I will work on that soon.
