### ISSUE TITLE
Limit popup size to screen resolution

### ISSUE THREAD

**Issue by anonimuos** [stnkl/EverythingToolbar#52]
Installed 0.6 stable on Windows 10 Enterprise 1803. It shows behind the Taskbar:
![image](https://user-images.githubusercontent.com/46422834/103119035-93e20000-4697-11eb-9c2f-2321f69d1af9.png)
https://i.imgur.com/MwPQeTs.png

I am running Open Shell for the Start menu, StartIsBack++ for skinning the taskbar and 7+ Taskbar Tweaker. Not sure if any of those change anything for the taskbar but anyway the taskbar is set to be always on top. 😊 But I disabled and Exited all but still, the Everything Toolbar search box appears behind the taskbar.

I am also running two other toolbars, could those be causing this? 
![image](https://user-images.githubusercontent.com/46422834/103119261-af99d600-4698-11eb-872b-6a0b45ec57fc.png)

Also, even though pressing Enter now launches the first item from the top, the item is not selected by default, so if I want to launch the 2nd item from the top, I have to press Down arrow key twice. Can this be changed so I only have to press it once, Enter to launch 2nd item? 😊

**Comment by stnkl** [comment]
Hard to see from the screenshot but does it go all the way up to the top screen edge? Can you grab a corner of the popup and drag it down to decrease the popup size? That might fix it.

**Comment by anonimuos** [comment]
Oh yes it goes all the way up to the top screen edge with a narrow gap above it. And yes, indeed dragging from the corner fixes it. :) 👍 Thank you! I didn't realize it was resizable from the top right corner. Tried resizing from the top edge - where nothing happened so I concluded it wasn't resizable. :)
