### ISSUE TITLE
Default windows search off?

### ISSUE THREAD

**Issue by IIEleven11** [stnkl/EverythingToolbar#53]
Does this only work when default windows search is turned on. I currently have it disabled through a 3rd party application. I dont like using it and just use everything pinned to my taskbar. I have the toolbar installed but am getting no functionality. Was wondering if its not podsible, possible, or a workaround?

**Comment by IIEleven11** [comment]
My fault. So everything i believe needs to be installed in its default directory for this to work. Originally I had it on my D drive which is not my boot drive its just a 1tb hdd for storage. This would cause no results. Once I installed to the C directory everything worked as intended.

**Comment by stnkl** [comment]
> I have the toolbar installed but am getting no functionality.

Does that mean no search results, no toolbar or an error message? It *should* work with Everything installed to non standard locations.
