### ISSUE TITLE
Preferences thru right click on Toolbar

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#54]
The version 0.6 final runs perfect for me
but I don't like the way to reach the settings now.
I first have to enter anything into the toolbar before I can get the settings.
I found the previous behavior to simply right click the toolbar much easier and more logical at least for the first setup. 
But the new method has benfits when I want to change things while typing.
So the best solution for me would be to have both ways available.

**Comment by stnkl** [comment]
I will probably just add whole word/match case etc. back to the search box context menu. Things like changing themes and managing rules don't need to be available from there in my opinion.

**Comment by Horst12** [comment]
> 
> 
> I will probably just add whole word/match case etc. back to the search box context menu. Things like changing themes and managing rules don't need to be available from there in my opinion.

Agreed
