### ISSUE TITLE
Incomplete display of the search window under taskbar

### ISSUE THREAD

**Issue by yqs112358** [stnkl/EverythingToolbar#56]
The search window is partly hidden under the taskbar just like this:

<img width="960" alt="屏幕截图 2020-12-27 102313" src="https://user-images.githubusercontent.com/37969157/103162600-92e2d700-482d-11eb-9967-ef35e396ee66.png">

And I am looking for an update for user-defined scaling in this toolbar since items seem too large in my 150% display scaling.

Set up:
- Laptop Zenbook U4700J whose monitor at 150% display scaling (1920x1080 resolution)
- Windows 10 2004
- EverythingToolbar 0.6.0 release version

**Comment by stnkl** [comment]
This is the same problem as in #52. You can reduce the popup size by dragging a corner of the popup. I will limit the popup size to the screen resolution in a future update.
