### ISSUE TITLE
Add non-English support（input method editor）

### ISSUE THREAD

**Issue by atticus-lv** [stnkl/EverythingToolbar#58]
I found it not able to type in Chinese to search files with the default Windows input method editor
![image](https://user-images.githubusercontent.com/64118610/103264739-8e155300-49e6-11eb-8e49-a801f4a219e3.png)
![image](https://user-images.githubusercontent.com/64118610/103264852-efd5bd00-49e6-11eb-9979-cfa40edbb206.png)

**Comment by stnkl** [comment]
Thanks for opening the issue. I noticed the "Address" toolbar that comes with Windows does not support PinYin either. Might be a limitation to deskbands. I'll have to find a workaround for that.
![image](https://user-images.githubusercontent.com/17520641/103381103-154bef00-4aeb-11eb-9528-f208613d2685.png)
