### ISSUE TITLE
No search results.

### ISSUE THREAD

**Issue by Cris--** [stnkl/EverythingToolbar#6]
Hi, great addon (if it works)! 

My search gives no results, white and empty popup! Only filters on top available.

Search Everything 1.4.1.992 Lite x64 (running as system service, works perfect)
Everything Toolbar 0.2.3 (installed via admin from c:\Tools\Everything Toolbar\)
Windows 10 Pro 20H2 Build 19042.508 x64

Some feature requests: Custom colors for background of the toolbar. Resizing of the result popup.

**Comment by stnkl** [comment]
Hi, could you please check the `%AppData%/Local/Temp/EverythingToolbar.log` for any exceptions? If there is none, please try if other applications using the Everything SDK work (for example [Wox](https://github.com/Wox-launcher)).

**Comment by stnkl** [comment]
It looks like Everything Lite [does not support IPC](https://www.voidtools.com/support/everything/installing_everything/) which is needed for EverythingToolbar. It should work with the full version of Everything for you. 

> Some feature requests: Custom colors for background of the toolbar. Resizing of the result popup.

Customizable colors will come when I get around to implementing light theme support, Also I can make the popup resizable. Thanks for the suggestions!

**Comment by Cris--** [comment]
> 
> 
> It looks like Everything Lite [does not support IPC](https://www.voidtools.com/support/everything/installing_everything/) which is needed for EverythingToolbar. It should work with the full version of Everything for you.

Ahh, ok. Then i will install the full version again. Anyway, log looks fine without error or something like that.
