### ISSUE TITLE
Open item context menu with keyboard shortcut

### ISSUE THREAD

**Issue by masterjian** [stnkl/EverythingToolbar#65]
After we searched the result, it can let us operate the target file easily.
This operation can support us only use the keyboard.

**Comment by stnkl** [comment]
Good idea, but we can't use the right arrows as it is already used to move the cursor within the search box. What would you suggest as an alternative? Maybe <kbd>Alt</kbd>+<kbd>Right</kbd>?

**Comment by masterjian** [comment]
the top filter bar: can we add the [Alt]+[prefix]  or [Alt]+ [Num] to activate the appropriate filter?
or [Alt]+[Num]  to show the context menu on the focused item?

**Comment by stnkl** [comment]
I think I would like to use <kbd>Ctrl</kbd>+<kbd>Number</kbd> to select filters/tabs as it is used in browsers like Chrome to navigate tabs.
The default Windows and [Everything](https://www.voidtools.com/support/everything/keyboard_shortcuts/) shortcut for opening file context menus seems to be <kbd>Shift</kbd>+<kbd>F10</kbd>.

**Comment by stnkl** [comment]
There are a few more keyboard and mouse shortcuts now which mostly make navigating the context menu obsolete. On top of that it would require quite significant changes to the application regarding how focus is handled which I don't think is worth it.

I'll close the issue for now.
