### ISSUE TITLE
no work on windows 10 家庭中文版20H2

### ISSUE THREAD

**Issue by cdslily** [stnkl/EverythingToolbar#66]
toolbar setting has checked  everything toolbar and everything has been installed!

**Comment by cdslily** [comment]
可以正常工作，只是在小图标，而不是在搜索栏。

**Comment by stnkl** [comment]
> 可以正常工作，只是在小图标，而不是在搜索栏。

Have a look at the [installation video](https://user-images.githubusercontent.com/17520641/102831521-4ee67100-43ec-11eb-8804-42dda8affba1.gif) for changing size and position.
