### ISSUE TITLE
unlaod the DLL from explorer process

### ISSUE THREAD

**Issue by eladpotok** [stnkl/EverythingToolbar#68]
Hi,

I spent couple of months of investigating the daskband.
Its seemed like there is no way to unload the DLL. 

I open Process Explorer and observe that the explorer owns the daskband DLL (EverythingToolbar) as long it is running.
Even if I unregister the daskband, the DLL still there so it blocks me for upgrading this daskband.

The only solution I have found is to restart explorer (kill explorer) or reboot (which is basically the same).
Does anyone find another solution? maybe something like "silence kill explorer" - something that will not make an impact on the user?

Thanks,

**Comment by stnkl** [comment]
I improved the (un)installing process a little bit. You don't have to explicitly run as admin anymore (it will elevate automatically) and after uninstalling it will restart explorer.exe to allow the dll to be overwritten. I currently don't know of any way to unlock the dll without restarting Explorer.

You can try it already by downloading the `install.cmd` and `uninstall.cmd` directly from [here](https://github.com/stnkl/EverythingToolbar/tree/master/EverythingToolbar/Inst).

**Comment by eladpotok** [comment]
Hi,
I change the installation to be non-admin as well, it is only about some registry key we should write in CLSID.
We need to change the write from Root to Current User (Root requires administration permission)

**Comment by stnkl** [comment]
> I change the installation to be non-admin as well, it is only about some registry key we should write in CLSID.
> We need to change the write from Root to Current User (Root requires administration permission).

You mean you got it to install completely without admin rights? I tried this method before but coudln't get it to work. Please let me know how you did it!

> Regarding to your comment, I guess that killing explorer (or reboot) is must, but do you know any better way to kill the explorer? something that would be more friendly?

What exactly do you mean by "more friendly"? I believe it is safe to just kill and restart explorer.exe. It takes maybe a second on my machine. Only downside is explorer windows closing.

**Comment by eladpotok** [comment]
> You mean you got it to install completely without admin rights? I tried this method before but coudln't get it to work. Please let me know how you did it!

When you register the toolbar into the taskbar it just writes to the registry. 
Go to root->software-classes->clsid
and search your daskband GUID.

All you need is to write it to the current-use->...->software->classes->clsid
its the same but without admin privilege's.

why do you need to code if you have here an install cmd file that doesn't need admin permission?
btw, Did you find any solution to avoid YES/NO prompt message when you Start the taskbar from the code?

>  What exactly do you mean by "more friendly"? I believe it is safe to just kill and restart explorer.exe. It takes maybe a second on my machine. Only downside is explorer windows closing.

I have an enterprise product , I don't want to force the users to "feel" that the taskbar disappeared and get back. its bad behavior, plus it clears the folders that are already opened.

**Comment by stnkl** [comment]
Thanks for the explanation!

> btw, Did you find any solution to avoid YES/NO prompt message when you Start the taskbar from the code?

I remember you from the other issue now! I still don't think this is possible due to security restrictions. But really not sure on this one, sorry.
