### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by mohcow** [stnkl/EverythingToolbar#7]
Title says it all, i'm using TranslucentTB to have a transparent taskbar, sadly EverythingToolbar stands out because it's not transparent.

**Comment by stnkl** [comment]
Thanks for the suggestion. This will be possible when I get around to implementing customizable colors. It will take a while though.

**Comment by stnkl** [comment]
Version 0.4.0 now supports theming. You can create a new theme file (.xaml) within the `Themes` folder and change each color individually. For example change the `SearchBoxBackground` color to `#00333333` to make it fully transparent.

![image](https://user-images.githubusercontent.com/17520641/98170435-45fa1880-1eee-11eb-99c3-c4fa51e2f49c.png)

**Comment by Dhyfer1** [comment]
> Version 0.4.0 now supports theming. You can create a new theme file (.xaml) within the `Themes` folder and change each color individually. For example change the `SearchBoxBackground` color to `#00333333` to make it fully transparent.
> 
> ![image](https://user-images.githubusercontent.com/17520641/98170435-45fa1880-1eee-11eb-99c3-c4fa51e2f49c.png)

What kind of color code is #00333333 ? Is HTML? Is Hex Code?

**Comment by stnkl** [comment]
> What kind of color code is #00333333 ? Is HTML? Is Hex Code?

It is an #AARRGGBB hex color code.

**Comment by Dhyfer1** [comment]
> > What kind of color code is #00333333 ? Is HTML? Is Hex Code?
> 
> It is an #AARRGGBB hex color code.

Thanks. Which application do you use to know color codes? I use [Instant Eyedropper](http://instant-eyedropper.com/) but I see that it does not support color coding like #AARRGGBB and I want to create a custom theme but I need an app that shows me those color values #AARRGGBB

**Comment by stnkl** [comment]
It looks like Instant Eyedropper gives you #RRGGBB. The AA in the front is just the transparency where FF would be fully opaque and 00 fully transparent. 

I'd suggest using an online [converter](https://www.rapidtables.com/convert/number/decimal-to-hex.html) to convert decimal 0-255 to hexadecimal 00-FF and prepending that to whatever Instant Eyedropper gives you. But most of the time you'll just need #FF...

**Comment by Dhyfer1** [comment]
> It looks like Instant Eyedropper gives you #RRGGBB. The AA in the front is just the transparency where FF would be fully opaque and 00 fully transparent.
> 
> I'd suggest using an online [converter](https://www.rapidtables.com/convert/number/decimal-to-hex.html) to convert decimal 0-255 to hexadecimal 00-FF and prepending that to whatever Instant Eyedropper gives you. But most of the time you'll just need #FF...

Hmmm 🤔 I see, okay. Thanks for your help, now it will take me a while to see what changes EverythingToolbar shows when I modify colors to create my custom theme. :)

**Comment by HulkSmashBurgers** [comment]
I searched the issues to see if the feature had been requested/added. Perhaps this info could be added to the README?
