### ISSUE TITLE
Not able to delete the dll files

### ISSUE THREAD

**Issue by pritz8** [stnkl/EverythingToolbar#72]
I wanted to remove everything toolbar (i liked it but parents didn't want it, sorry!) but the dll files are not deleting. As said earlier by another guy here, it shows up as an active windows explorer action.

How do I fix this problem to remove it?

**Comment by stnkl** [comment]
After disabling the toolbar from the taskbar context menu either restart your computer or explorer.exe from the taskmanager. After that you should be able to remove the dll. 

In case the toolbar pops up again after restarting make sure to wait a little while after disabling it so Windows can "remember" is has been disabled before you restart.

**Comment by pritz8** [comment]
It worked! Thanks. But very sorry I had to delete it. It was great having it!

**Comment by stnkl** [comment]
Don't worry about it. 😊
