### ISSUE TITLE
Add Windows light theme support

### ISSUE THREAD

**Issue by Susko3** [stnkl/EverythingToolbar#73]
Right now, the search icon (and it's active/hover background color) only for Windows dark theme. When you set Windows to light theme, your app's icon is white on white, it should be black on white.

**Comment by tech189** [comment]
You can check for this straight from the registry:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize`
If AppsUseLightTheme is 0, then the theme is dark, if it's 1, then the light theme is active on the task bar.

**Comment by Keagel** [comment]
Relating to that - I think it would be nice to have a fourth theme option that follows the system theme. I'm using an utility called "Auto Dark Mode" which enables me to change the theme to dark/light based on sunrise/sunset, so that would be pretty convenient.

**Comment by Susko3** [comment]
@Keagel what the code is doing is exactly that; it'll follow the system dark theme.

**Comment by Keagel** [comment]
> 
> 
> @Keagel what the code is doing is exactly that; it'll follow the system dark theme.

Do you mean the commit referenced in this issue does that? Because reading the code it seems it's only for the icon.

**Comment by stnkl** [comment]
Yes, the committed code only changes the icon color at launch. It does not react to theme changes either. I'll continue working on that soon.

An auto light/dark theme might come in the future but not very soon.

**Comment by Susko3** [comment]
The hover background changes in Windows light theme. So you should change that in addition to the icon's color. (I'm not talking about the tooltip)

![image](https://user-images.githubusercontent.com/16479013/104734477-a0aabe80-5740-11eb-9bcb-0f7999844244.png)

**Comment by stnkl** [comment]
> The hover background changes in Windows light theme. So you should change that in addition to the icon's color. (I'm not talking about the tooltip)
> 
> ![image](https://user-images.githubusercontent.com/16479013/104734477-a0aabe80-5740-11eb-9bcb-0f7999844244.png)

I'm already aware of that and will work on that soon. I'll also make the icon color react to Windows theme changes for the next release.

**Comment by LinqLover** [comment]
I have installed v0.6.2.0 but it's still looking wrong for me:

![image](https://user-images.githubusercontent.com/38782922/105484302-68106500-5cab-11eb-80ff-af960d46606f.png)

(The screenshot from the settings app says: "Standard windows mode - dark, standard app mode - light", using win 2004)

**Comment by stnkl** [comment]
Yes, sorry about that. I was notified of that in #94 and it is already fixed. Will be available in the next beta in a few days.

**Comment by ShahedFaisal** [comment]
Hi, @stnkl. Is there any ETA for the auto dark/light theme feature? It would be very convinient. Great tool, by the way!

**Comment by stnkl** [comment]
> Hi, @stnkl. Is there any ETA for the auto dark/light theme feature? It would be very convinient. Great tool, by the way!

Hi @ShahedFaisal , currently I am not sure. I am quite busy with other projects at the moment but will get back to EverythingToolbar in a few weeks or months.
