### ISSUE TITLE
Add support for TaskbarX or other rainmeter applications

### ISSUE THREAD

**Issue by thebluedev** [stnkl/EverythingToolbar#74]
Is it possible? currently adding the toolbar while having taskbarX does not let me open or close the toolbar. I had to unload the skin 
change the toolbar and reload, even with that it is janky, you cannot resize it and also it goes bonkers when you have the taskbar set to auto-hide

**Comment by stnkl** [comment]
Just tried TaskbarX for the first time. It looks like the same issue appears for other toolbars like Windows' default address toolbar. That's why I think this is an issue on TaskbarX's side.

Auto-hiding taskbars are currently not fully supported in EverythingToolbar (#4).
