### ISSUE TITLE
Could this work with PowerToys Run?

### ISSUE THREAD

**Issue by RekiDunois** [stnkl/EverythingToolbar#78]
PowerToys Run can search file, but it use Windows Search. If we can use Everything in PowerToys Run, that would be awesome.

**Comment by stnkl** [comment]
I agree. Everything has its own [SDK](https://www.voidtools.com/support/everything/sdk/) which EverythingToolbar is using to retrieve search results. PowerToys Run would need to implement this functionality itself.

It looks like it has already been discussed here: https://github.com/microsoft/PowerToys/pull/4364
