### ISSUE TITLE
Support Windows key shortcuts

### ISSUE THREAD

**Issue by Shnxxx** [stnkl/EverythingToolbar#79]
Frankly speaking, this app is great! It could replace Cortana already. Anw, I have this problem changing shortcut. I would like to change the shortcut to `Win+space` but when I try to press `Win` instead of capturing it, it lets me open the Windows menu.
Also, tried typing `Win` manually (nothing will be lost if I didn't try) but yeah, as expected, it captures `W`.

I have some couple of ideas for the app. Just tell me if you would like to hear it.

Oh btw, When there is an open window from `EverythingToobar` like the shortcut window, I couldn't able to use the taskbar.

**Comment by stnkl** [comment]
<kbd>Win</kbd>+<kbd>Key</kbd> shortcuts are currently not supported due to a limitation of [NHotkey](https://github.com/thomaslevesque/NHotkey/issues/21). You can use <kbd>Alt</kbd>+<kbd>Space</kbd> instead.

The shortcut window blocks taskbar inputs but other windows don't.

**Comment by PurpleSwords** [comment]
I have tried the keyboard hook WH_KEYBOARD_LL, which can override system shortcuts such as win+s. You can try to use it.

**Comment by emilheunecke** [comment]
> I have tried the keyboard hook WH_KEYBOARD_LL, which can override system shortcuts such as win+s. You can try to use it.

@stnkl Are you certain that you won't add winkey support?

**Comment by stnkl** [comment]
Thanks @PurpleSwords for bringing the low level keyboard hooks to my attention! They are now being used inside the shortcut selection dialog. However for actually capturing the shortcuts the old approach is still used requiring an explorer restart when changing to a <kbd>Win</kbd>+<kbd>Key</kbd> shortcut. Unfortunately some shortcuts like <kbd>Win</kbd>+<kbd>Space</kbd> or <kbd>Win</kbd>+<kbd>Enter</kbd> are still blocked by the system.

These changes will be available in the next release.
