### ISSUE TITLE
[Enhancement] Add copy-paste function to search result

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [stnkl/EverythingToolbar#8]
Sometimes I need to copy and paste the searched result, file or folder, elsewhere. Would be nice if I could do that by just ctrl+v/c.

**Comment by stnkl** [comment]
As I want the text box to always be keyboard focused while the popup is open I would rather not hijack Ctrl+C to copy anything other than the text box contents. However @Ylevo implemented the ability to copy file paths from the context menu of search result items in #14.

**Comment by stnkl** [comment]
You can now copy file paths or whole files from within the context menu of search results. Check out today's prerelease of version 0.3.0-beta1!
