### ISSUE TITLE
"IPC is not available"

### ISSUE THREAD

**Issue by falcorr** [stnkl/EverythingToolbar#82]
AppData\Local\Temp\EverythingToolbar.log:
2021-01-11 23:03:12.9101|ERROR|IPC is not available.|

How might I fix this? I get absolutely no results.

**Comment by stnkl** [comment]
Is [Everything](https://www.voidtools.com) running in the background? The Lite version is not supported.

**Comment by falcorr** [comment]
I had grabbed Everything as well initially, I don't remember if it was the Lite version. I've seen no mention of it in Task Manager or Process Explorer. 

I believe it was portable. It didn't appear in Programs and Features for uninstall. I just deleted the directory. Removed and re-added the toolbar, no change.

**Comment by stnkl** [comment]
Everything has to be running in the background. It is the backend needed for EverythingToolbar to retrieve search results. If there is no indication in the system tray or task manager it looks like it is not running.

Please download Everything again (portable or installer doesn't matter) and have it running in the background. Afterwards EverythingToolbar should give you search results.

**Comment by falcorr** [comment]
That seems to have done it.

I had no idea I needed Everything as well. There doesn't seem to be any mention of this.

**Comment by stnkl** [comment]
> That seems to have done it.
> 
> I had no idea I needed Everything as well. There doesn't seem to be any mention of this.

Glad it's working now! It's actually mentioned in the [requirements](https://github.com/stnkl/EverythingToolbar#requirements). 😊

**Comment by falcorr** [comment]
Oh, whoops. Unless it's something that needs compiling, I tend to safely assume I have all that's needed. I just filtered everything out except the Install instructions!

Thanks for the speedy help.
