### ISSUE TITLE
UWP apps do not appear in search.

### ISSUE THREAD

**Issue by Darkwolf1515** [stnkl/EverythingToolbar#83]
Not sure if that's the fault of everything or the fault of the taskbar, but it would be great to be able to see them,

**Comment by stnkl** [comment]
I don't think you can search for UWP applications with Everything.

In the future I plan on adding a plugin system to retrieve search results from other applications but that will not happen very soon.

You might want to look into something like Wox:

https://github.com/Wox-launcher/Wox
