### ISSUE TITLE
Is there a way to make shortcuts appear first?

### ISSUE THREAD

**Issue by Darkwolf1515** [stnkl/EverythingToolbar#84]
Basically, when I say, search for steam, it will first suggest not steam,exe. but the steam shortcut.

**Comment by stnkl** [comment]
One possible way would be to

1. Create a custom filter like this within Everything: 
![image](https://user-images.githubusercontent.com/17520641/104293490-5adec380-54be-11eb-9364-382f68b2adaf.png)
2. Enable "Use Everything filters" within EverythingToolbars settings
3. Select the filter manually or by pressing <kbd>Tab</kbd>/<kbd>Shift</kbd>+<kbd>Tab</kbd> when searching with EverythingToolbar

If you set it up to be the last filter all you have to do is press <kbd>Shift</kbd>+<kbd>Tab</kbd> when searching to only list start menu shortcuts.
