### ISSUE TITLE
Regular Expressions in Everything Filters Don't Function

### ISSUE THREAD

**Issue by SkyNinja** [stnkl/EverythingToolbar#88]
When a filter utilizing regex is selected in Everything Toolbar, the contents of the regex seem to be searched literally. 

I have a filter that uses regex to remove log, prefetch and shortcut files from results.
This is the regex used:
`^(?!.*\.(?:pf|log|lnk)$)`
This is an example of the results using the filter in Everything:
![2021-01-15 (1)](https://user-images.githubusercontent.com/4765557/104792677-d19cea80-5764-11eb-98d6-3d96f0f83529.png)
And this is the results when using the filter in Everything Toolbar:
![2021-01-15 (3)](https://user-images.githubusercontent.com/4765557/104792695-e5485100-5764-11eb-8045-de43cfe29f27.png)

**Comment by Horst12** [comment]
I guess the Toolbar is not honoring the regex flag in your filter.
As a work-around I would try to add regex: in the search field of your filter.

**Comment by stnkl** [comment]
I made custom filters overwrite the RegEx/match case etc. settings from filters. I noticed however that Everything itself doesn't seem to respect e.g. match case flag. I'd like EverythingToolbar to have the same filter behaviour as Everything. But for that I have to understand its original behaviour first. Any ideas?
