### ISSUE TITLE
32-Bit OS Support

### ISSUE THREAD

**Issue by zafzal3** [stnkl/EverythingToolbar#90]
Windows 32 bit installation is currently not supported by install.cmd!

**Comment by stnkl** [comment]
You can try replacing the original files with these ones. [32bit_install.zip](https://github.com/stnkl/EverythingToolbar/files/5837739/32bit_install.zip)

Keep in mind this is the Everything32.dll renamed to Everything64.dll.

Let me know if this works for you.

**Comment by stnkl** [comment]
I tried it on a 32 bit virtual machine and there appears to be a [problem with CSDeskBand](https://github.com/dsafa/CSDeskBand/issues/58) causing an explorer.exe freeze after a few seconds of activating a toolbar. I might look into this at some point but for now 32 bit Windows will not be supported.

**Comment by stnkl** [comment]
I will close this issue, since the demand seems to be very low and 32 bit will not exist anymore in the future (as already observed in Windows 11).
