### ISSUE TITLE
Why QuickLook and not Explorer preview or configurable

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#93]
As the subject says ?
Everything uses Explorer preview and can display most popular file formats and more depending on installed programs.
QuickLook crashes if used from inside of Everything and on many other places.
It works from the toolbar but doesn't remember its size and position.

**Comment by stnkl** [comment]
It has been requested by a user in #61. QuickLook works fine for me from within Everything and EverythingToolbar.

**Comment by Horst12** [comment]
> 
> 
> It has been requested by a user in #61. QuickLook works fine for me from within Everything and EverythingToolbar.

For me it works in the Toolbar but not in newest Everything (x64 version 1003)..
If I use the space key on a pdf file in Everything results QuickLook simply terminates in the background
and I have to restart it.

**Comment by stnkl** [comment]
Sorry, but you have to post that issue here: https://github.com/QL-Win/QuickLook/issues

**Comment by Horst12** [comment]
> 
> 
> Sorry, but you have to post that issue here: https://github.com/QL-Win/QuickLook/issues

Done
