### ISSUE TITLE
Themeing does not match Windows mode theme

### ISSUE THREAD

**Issue by jamesmendel** [stnkl/EverythingToolbar#94]
The color (light/dark) of the icon is synced with default app mode color. It should follow Windows mode (if that is possible) in order to follow system-wide styling.
See pictures below:

![image](https://user-images.githubusercontent.com/6820045/105095557-6eb09980-5a6b-11eb-8a47-ea17c8d0b9ae.png)

**Comment by jamesmendel** [comment]
Changing theme from `Preferences > Theme` does not seem to effect the icon.

**Comment by stnkl** [comment]
I didn't know you could set them individually. But that's an easy fix. Thank you!

**Comment by jacksongoode** [comment]
Hi, @stnkl I'm on 0.62, Windows 1809 LTSC and I still have this issue (a black search icon over a black toolbar).

**Comment by stnkl** [comment]
@jacksongoode, thanks for letting me know! It should be fixed in the next release.
