### ISSUE TITLE
Animations lagging

### ISSUE THREAD

**Issue by LinqLover** [stnkl/EverythingToolbar#95]
Just stumbled upon this tool, great idea with a lot of potentials! Just one disadvantage I have noticed so far: While my built-in Windows search view pops up in a very smooth way, the everything toolbar looks really lagging (max. 10 fps). It would be fantastic if you could fix this bug ... :)

**Comment by Fayyaadh** [comment]
I just installed this yesterday and it was fine but today I see that the animation is slightly laggy right at the beginning.

**Comment by stnkl** [comment]
Opening and closing animations have been improved in the [1.0.0 release](https://github.com/stnkl/EverythingToolbar/releases/tag/1.0.0).
