### ISSUE TITLE
[feature request] get recent searches via button and/or up arrow

### ISSUE THREAD

**Issue by d0nh** [stnkl/EverythingToolbar#96]
First, I want to thank you for this amazing little helper. It really improves the Windows experience to finally have an easily accessible, actual good search.
 
My feature request would be this: How about a search history where all recent search strings could be re-entered simply by pressing the up arrow or a UI button (like in a console where up arrow skips through all recent entries)? I think this would be a great improvement. Let me know whether it's possible or if you'd like to implement something similar.

Greetings

**Comment by stnkl** [comment]
Thanks. This has been requested in #24 before. It will come at some point.

Closing duplicate.
