### ISSUE TITLE
[feature request] simple number showing the amount of search results

### ISSUE THREAD

**Issue by d0nh** [stnkl/EverythingToolbar#97]
The Everything window has a little bar at the bottom which simply shows the amount of search results and it's constantly updated while typing.
Would it be possible / make sense to show this on the task bar helper as well?

**Comment by stnkl** [comment]
I added an option to display the number of search results:

![grafik](https://user-images.githubusercontent.com/17520641/121089793-f105e400-c7e7-11eb-87fa-b918fd33f267.png)

It will be available in the next release.
