### ISSUE TITLE
when I open install.cmd as administrator I get this ERROR! plz help

### ISSUE THREAD

**Issue by David07799** [stnkl/EverythingToolbar#98]
when I open install.cmd as administrator I get this ERROR:

"RegAsm : error RA0000 : Unable to locate input assembly 'C:\Program Files\EverythingToolbar-master\EverythingToolbar\tools\..\bin\Release\EverythingToolbar.dll' or one of its dependencies."

I have "everything" running
I have .net and visual installed too? 
plz help

**Comment by stnkl** [comment]
I think you downloaded the source code. Please delete the "EverythingToolbar-master" folder and download the correct files from the [releases](https://github.com/stnkl/EverythingToolbar/releases). Click on "Assets" and download "[EverythingToolbar-0.6.2-beta1.zip](https://github.com/stnkl/EverythingToolbar/releases/download/0.6.2-beta1/EverythingToolbar-0.6.2-beta1.zip)".

**Comment by David07799** [comment]
yes that's true, it's fixed now
