### ISSUE TITLE
Highlighting Everything Toolbar Box and Pressing Alt+F4 Crashes Explorer

### ISSUE THREAD

**Issue by SkyNinja** [stnkl/EverythingToolbar#99]
Having Everything Toolbar active and pressing Alt+F4 crashes explorer.
The issue initially made itself known to me when I tried to initiate a shutdown with Alt+F4. The toolbar had been highlighted by default after closing other windows, and caused my desktop to crash. After further testing, I found the issue to be easily repeatable.

**Comment by stnkl** [comment]
Thank you for opening the issue. Is there any way for you to consistently reproduce the toolbar setting focus to itself? You mentioned it happened after closing all other windows but it doesn't get focused for me that way.

The Alt+F4 problem however is easily reproducible of course.

**Comment by SkyNinja** [comment]
No problem.

1. Click in the toolbar to make it active
2. Open another program (web browser or explorer window for my testing)
3. Close the other app with Alt+F4

The toolbar is highlighted sometimes when I close an app with the mouse, but it seems to be highlighted every time I close with Alt+F4.

On another note, possibly related, the toolbar looks like it's highlighted now, as I'm typing this. It's not receiving input, since my browser is what's actually active, but it's darkened and blinking as though it's awaiting input.

**Comment by stnkl** [comment]
I remember this "pseudo-focus" has been a problem in the very early versions of EverythingToolbar but should be fixed by now. Which version are you running? 

Unfortunately I can not reproduce this behaviour on my end using those steps but I'll fix the crash in the meantime.

**Comment by SkyNinja** [comment]
I'm running 0.6.1.0.

**Comment by stnkl** [comment]
Thanks, I fixed it and it will be available in the next release!
